// Generated by esidl 0.4.0.

package org.w3c.dom.css;

public interface CSSColorComponentValue
{
    // CSSColorComponentValue
    public short getRed();
    public void setRed(short red);
    public short getGreen();
    public void setGreen(short green);
    public short getBlue();
    public void setBlue(short blue);
    public float getAlpha();
    public void setAlpha(float alpha);
}
