// Generated by esidl 0.4.0.

package org.w3c.dom.css;

public interface CSSKeywordComponentValue
{
    // CSSKeywordComponentValue
    public String getKeyword();
    public void setKeyword(String keyword);
}
