// Generated by esidl 0.4.0.

package org.w3c.dom.css;

public interface CSSLengthComponentValue
{
    // CSSLengthComponentValue
    public float getEm();
    public void setEm(float em);
    public float getEx();
    public void setEx(float ex);
    public float getPx();
    public void setPx(float px);
}
