// Generated by esidl 0.4.0.

package org.w3c.dom.css;

import org.w3c.dom.Element;

public interface DocumentCSS
{
    // DocumentCSS
    public CSSStyleDeclaration getOverrideStyle(Element elt, String pseudoElt);
}
