/*-------------------------------------------------------
 * This file was generated by XpeCodeGen
 * Version 1.0.0
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.math.Matrix4;
import com.badlogic.gdx.utils.Array;

/**
 * @author xpenatan
 */
public class btCompoundShape extends btCollisionShape {

    protected Array<btCollisionShape> children = new Array<btCollisionShape>();

    public btCompoundShape() {
        resetObj(createNative(), true);
    }

    protected void cacheObj() {
        com.dragome.commons.javascript.ScriptHelper.put("addr", this.cPointer, this);
        this.jsObj = com.dragome.commons.javascript.ScriptHelper.eval("Bullet.wrapPointer(addr,Bullet.btCompoundShape);", this);
    }

    public static long createNative() {
        return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(new Bullet.btCompoundShape());", null);
    }

    @Override
    protected void delete() {
        super.delete();
        children.clear();
    }

    public void addChildShape(Matrix4 localTransform, btCollisionShape shape) {
        checkPointer();
        com.dragome.commons.javascript.ScriptHelper.put("jsObj", this.jsObj, this);
        com.dragome.commons.javascript.ScriptHelper.put("shapeObj", shape.jsObj, this);
        com.dragome.commons.javascript.ScriptHelper.put("value", localTransform.val, this);
        com.dragome.commons.javascript.ScriptHelper.evalNoResult("var tran=Bullet.MyTemp.prototype.btTran();tran.setFromOpenGLMatrix(value);jsObj.addChildShape(tran,shapeObj);", this);
        children.add(shape);
    }

    public void removeChildShape(btCollisionShape shape) {
        checkPointer();
        com.dragome.commons.javascript.ScriptHelper.put("jsObj", this.jsObj, this);
        com.dragome.commons.javascript.ScriptHelper.put("shapeObj", shape.jsObj, this);
        com.dragome.commons.javascript.ScriptHelper.evalNoResult("jsObj.removeChildShape(shapeObj);", this);
        children.removeValue(shape, true);
    }

    public int getNumChildShapes() {
        return children.size;
    }

    public btCollisionShape getChildShape(int index) {
        return children.get(index);
    }
}
