/*-------------------------------------------------------
 * This file was generated by XpeCodeGen
 * Version 1.0.0
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

/**
 * @author xpenatan
 */
public class btPolyhedralConvexShape extends btConvexInternalShape {

    protected void cacheObj() {
        com.dragome.commons.javascript.ScriptHelper.put("addr", this.cPointer, this);
        this.jsObj = com.dragome.commons.javascript.ScriptHelper.eval("Bullet.wrapPointer(addr,Bullet.btConvexInternalShape);", this);
    }
}
