// Generated by esidl 0.4.0.

package org.w3c.dom.webgl;

import org.w3c.dom.events.Event;

public interface WebGLContextEvent extends Event
{
    // WebGLContextEvent
    public String getStatusMessage();
    public void initWebGLContextEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, String statusMessageArg);
}
