// Generated by esidl 0.4.0.

package org.w3c.dom.stylesheets;

public interface MediaList
{
    // MediaList
    public String getMediaText();
    public void setMediaText(String mediaText);
    public int getLength();
    public String item(int index);
    public void appendMedium(String medium);
    public void deleteMedium(String medium);
}
