// Generated by esidl 0.4.0.

package org.w3c.dom.stylesheets;

import org.w3c.dom.Node;

public interface StyleSheet
{
    // StyleSheet
    public String getType();
    public String getHref();
    public Node getOwnerNode();
    public StyleSheet getParentStyleSheet();
    public String getTitle();
    public MediaList getMedia();
    public void setMedia(String media);
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
}
