// Generated by esidl 0.4.0.

package org.w3c.dom.file;

public interface Blob
{
    // Blob
    public long getSize();
    public String getType();
    public Blob slice(long start, long length);
    public Blob slice(long start, long length, String contentType);
}
