// Generated by esidl 0.4.0.

package org.w3c.dom.file;

public class FileException extends RuntimeException
{
    public FileException(short code, String message)
    {
        super(message);
        this.code = code;
    }
    public static final short NOT_FOUND_ERR = 1;
    public static final short SECURITY_ERR = 2;
    public static final short ABORT_ERR = 3;
    public static final short NOT_READABLE_ERR = 4;
    public static final short ENCODING_ERR = 5;
    public short code;
}
