// Generated by esidl 0.4.0.

package org.w3c.dom.file;

import org.w3c.dom.events.EventTarget;
import org.w3c.dom.html.Function;

public interface FileReader extends EventTarget
{
    // FileReader
    public void readAsArrayBuffer(Blob blob);
    public void readAsBinaryString(Blob blob);
    public void readAsText(Blob blob);
    public void readAsText(Blob blob, String encoding);
    public void readAsDataURL(Blob blob);
    public void abort();
    public static final short EMPTY = 0;
    public static final short LOADING = 1;
    public static final short DONE = 2;
    public short getReadyState();
    public Object getResult();
    public FileError getError();
    public Function getOnloadstart();
    public void setOnloadstart(Function onloadstart);
    public Function getOnprogress();
    public void setOnprogress(Function onprogress);
    public Function getOnload();
    public void setOnload(Function onload);
    public Function getOnabort();
    public void setOnabort(Function onabort);
    public Function getOnerror();
    public void setOnerror(Function onerror);
    public Function getOnloadend();
    public void setOnloadend(Function onloadend);
}
