/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.dynamics;

/** @author xpenatan */
public class btSequentialImpulseConstraintSolver extends btConstraintSolver {

    public btSequentialImpulseConstraintSolver() {
        resetObj(createNative(), true);
    }

    private static long createNative() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var obj=new Bullet.btSequentialImpulseConstraintSolver();",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(obj);",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btSequentialImpulseConstraintSolver);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var cobj=Bullet.wrapPointer(addr,Bullet.btSequentialImpulseConstraintSolver);Bullet.destroy(cobj);",this);
    }
}
