// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface Attr
{
    // Attr
    public String getNamespaceURI();
    public String getPrefix();
    public String getLocalName();
    public String getName();
    public String getValue();
    public void setValue(String value);
}
