// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface CharacterData extends Node
{
    // CharacterData
    public String getData();
    public void setData(String data);
    public int getLength();
    public String substringData(int offset, int count);
    public void appendData(String data);
    public void insertData(int offset, String data);
    public void deleteData(int offset, int count);
    public void replaceData(int offset, int count, String data);
}
