// Generated by esidl 0.4.0.

package org.w3c.dom;

import org.w3c.dom.ObjectArray;
import org.w3c.dom.events.Event;
import org.w3c.dom.stylesheets.StyleSheet;

public interface Document extends Node
{
    // Document
    public DOMImplementation getImplementation();
    public String getDocumentURI();
    public void setDocumentURI(String documentURI);
    public String getCompatMode();
    public String getCharset();
    public void setCharset(String charset);
    public String getCharacterSet();
    public String getDefaultCharset();
    public String getContentType();
    public DocumentType getDoctype();
    public Element getDocumentElement();
    public NodeList getElementsByTagName(String qualifiedName);
    public NodeList getElementsByTagNameNS(String namespace, String localName);
    public NodeList getElementsByClassName(String classNames);
    public Element getElementById(String elementId);
    public Element createElement(String localName);
    public Element createElementNS(String namespace, String qualifiedName);
    public DocumentFragment createDocumentFragment();
    public Text createTextNode(String data);
    public Comment createComment(String data);
    public ProcessingInstruction createProcessingInstruction(String target, String data);
    public Node importNode(Node node, boolean deep);
    public Node adoptNode(Node node);
    public Event createEvent(String eventInterfaceName);
    // Document-1
    public ObjectArray<StyleSheet> getStyleSheets();
    public String getSelectedStyleSheetSet();
    public void setSelectedStyleSheetSet(String selectedStyleSheetSet);
    public String getLastStyleSheetSet();
    public String getPreferredStyleSheetSet();
    public DOMStringList getStyleSheetSets();
    public void enableStyleSheetsForSet(String name);
    // Document-2
    public Element elementFromPoint(float x, float y);
    public CaretPosition caretPositionFromPoint(float x, float y);
    // NodeSelector
    public Element querySelector(String selectors);
    public NodeList querySelectorAll(String selectors);
}
