// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface DOMElementMap
{
    // DOMElementMap
    public String getElement(String name);
    public void setElement(String name, Element value);
    public void createElement(String name, Element value);
    public void deleteElement(String name);
}
