// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface DoubleArray
{
    // DoubleArray
    public int getLength();
    public void setLength(int length);
    public double getElement(int index);
    public void setElement(int index, double value);
}
