// Generated by esidl 0.4.0.

package org.w3c.dom;

import org.w3c.dom.ObjectArray;
import org.w3c.dom.html.HTMLCollection;
import org.w3c.dom.views.ClientRect;
import org.w3c.dom.views.ClientRectList;

public interface Element extends Node
{
    // Element
    public String getNamespaceURI();
    public String getPrefix();
    public String getLocalName();
    public String getTagName();
    public ObjectArray<Attr> getAttributes();
    public String getAttribute(String qualifiedName);
    public String getAttributeNS(String namespace, String localName);
    public void setAttribute(String qualifiedName, String value);
    public void setAttributeNS(String namespace, String qualifiedName, String value);
    public void removeAttribute(String qualifiedName);
    public void removeAttributeNS(String namespace, String localName);
    public boolean hasAttribute(String qualifiedName);
    public boolean hasAttributeNS(String namespace, String localName);
    public NodeList getElementsByTagName(String qualifiedName);
    public NodeList getElementsByTagNameNS(String namespace, String localName);
    public NodeList getElementsByClassName(String classNames);
    public HTMLCollection getChildren();
    public Element getFirstElementChild();
    public Element getLastElementChild();
    public Element getPreviousElementSibling();
    public Element getNextElementSibling();
    public int getChildElementCount();
    // Element-3
    public ClientRectList getClientRects();
    public ClientRect getBoundingClientRect();
    public void scrollIntoView();
    public void scrollIntoView(boolean top);
    public int getScrollTop();
    public void setScrollTop(int scrollTop);
    public int getScrollLeft();
    public void setScrollLeft(int scrollLeft);
    public int getScrollWidth();
    public int getScrollHeight();
    public int getClientTop();
    public int getClientLeft();
    public int getClientWidth();
    public int getClientHeight();
    // NodeSelector
    public Element querySelector(String selectors);
    public NodeList querySelectorAll(String selectors);
}
