// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface FloatArray
{
    // FloatArray
    public int getLength();
    public void setLength(int length);
    public float getElement(int index);
    public void setElement(int index, float value);
}
