// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface LongLongArray
{
    // LongLongArray
    public int getLength();
    public void setLength(int length);
    public long getElement(int index);
    public void setElement(int index, long value);
}
