// Generated by esidl 0.4.0.

package org.w3c.dom;

import org.w3c.dom.events.EventTarget;

public interface Node extends EventTarget
{
    // Node
    public static final short ELEMENT_NODE = 1;
    public static final short ATTRIBUTE_NODE = 2;
    public static final short TEXT_NODE = 3;
    public static final short CDATA_SECTION_NODE = 4;
    public static final short ENTITY_REFERENCE_NODE = 5;
    public static final short ENTITY_NODE = 6;
    public static final short PROCESSING_INSTRUCTION_NODE = 7;
    public static final short COMMENT_NODE = 8;
    public static final short DOCUMENT_NODE = 9;
    public static final short DOCUMENT_TYPE_NODE = 10;
    public static final short DOCUMENT_FRAGMENT_NODE = 11;
    public static final short NOTATION_NODE = 12;
    public short getNodeType();
    public String getNodeName();
    public String getBaseURI();
    public Document getOwnerDocument();
    public Node getParentNode();
    public Element getParentElement();
    public boolean hasChildNodes();
    public NodeList getChildNodes();
    public Node getFirstChild();
    public Node getLastChild();
    public Node getPreviousSibling();
    public Node getNextSibling();
    public static final short DOCUMENT_POSITION_DISCONNECTED = 0x01;
    public static final short DOCUMENT_POSITION_PRECEDING = 0x02;
    public static final short DOCUMENT_POSITION_FOLLOWING = 0x04;
    public static final short DOCUMENT_POSITION_CONTAINS = 0x08;
    public static final short DOCUMENT_POSITION_CONTAINED_BY = 0x10;
    public static final short DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC = 0x20;
    public short compareDocumentPosition(Node other);
    public String getNodeValue();
    public void setNodeValue(String nodeValue);
    public String getTextContent();
    public void setTextContent(String textContent);
    public Node insertBefore(Node newChild, Node refChild);
    public Node replaceChild(Node newChild, Node oldChild);
    public Node removeChild(Node oldChild);
    public Node appendChild(Node newChild);
    public Node cloneNode(boolean deep);
    public boolean isSameNode(Node node);
    public boolean isEqualNode(Node node);
    public String lookupPrefix(String namespace);
    public String lookupNamespaceURI(String prefix);
    public boolean isDefaultNamespace(String namespace);
}
