// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface ProcessingInstruction extends Node
{
    // ProcessingInstruction
    public String getTarget();
    public String getData();
    public void setData(String data);
}
