// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface Text extends CharacterData
{
    // Text
    public Text splitText(int offset);
    public String getWholeText();
    public Text replaceWholeText(String data);
}
