// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface UnsignedByteArray
{
    // UnsignedByteArray
    public int getLength();
    public void setLength(int length);
    public byte getElement(int index);
    public void setElement(int index, byte value);
}
