// Generated by esidl 0.4.0.

package org.w3c.dom;

import org.w3c.dom.events.EventTarget;
import org.w3c.dom.html.Function;

public interface XMLHttpRequestEventTarget extends EventTarget
{
    // XMLHttpRequestEventTarget
    public Function getOnloadstart();
    public void setOnloadstart(Function onloadstart);
    public Function getOnprogress();
    public void setOnprogress(Function onprogress);
    public Function getOnabort();
    public void setOnabort(Function onabort);
    public Function getOnerror();
    public void setOnerror(Function onerror);
    public Function getOnload();
    public void setOnload(Function onload);
    public Function getOntimeout();
    public void setOntimeout(Function ontimeout);
    public Function getOnloadend();
    public void setOnloadend(Function onloadend);
}
