// Generated by esidl 0.4.0.

package com.github.xpenatan.gdx.backend.web.dom.typedarray;

public interface ArrayBufferViewWrapper {
	// ArrayBufferView
	public ArrayBufferWrapper getBuffer();

	public int getByteOffset();

	public int getByteLength();
}
