// Generated by esidl 0.4.0.

package com.github.xpenatan.gdx.backend.web.dom.typedarray;

public interface FloatArray
{
    // FloatArray
    public int getLength();
    public void setLength(int length);
    public float getElement(int index);
    public void setElement(int index, float value);
}
