// Generated by esidl 0.4.0.

package com.github.xpenatan.gdx.backend.web.dom.typedarray;

public interface LongArray {
	// LongArray
	public int getLength();

	public void setLength(int length);

	public int getElement(int index);

	public void setElement(int index, int value);
}
