// Generated by esidl 0.4.0.

package org.w3c.dom.events;

public interface Event_Constructor
{
    // Constructor
    public Event createInstance(String type);
    public Event createInstance(String type, EventInit eventInitDict);
}
