// Generated by esidl 0.4.0.

package org.w3c.dom.events;

import org.w3c.dom.html.Window;

public interface MouseEvent extends UIEvent
{
    // MouseEvent
    public int getScreenX();
    public int getScreenY();
    public int getClientX();
    public int getClientY();
    public boolean getCtrlKey();
    public boolean getShiftKey();
    public boolean getAltKey();
    public boolean getMetaKey();
    public short getButton();
    public short getButtons();
    public EventTarget getRelatedTarget();
    public void initMouseEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Window viewArg, int detailArg, int screenXArg, int screenYArg, int clientXArg, int clientYArg, boolean ctrlKeyArg, boolean altKeyArg, boolean shiftKeyArg, boolean metaKeyArg, short buttonArg, EventTarget relatedTargetArg);
    public boolean getModifierState(String keyArg);
    // MouseEvent-40
    public int getPageX();
    public int getPageY();
    public int getX();
    public int getY();
    public int getOffsetX();
    public int getOffsetY();
}
