// Generated by esidl 0.4.0.

package org.w3c.dom.events;

public interface MutationEvent extends Event
{
    // MutationEvent
    public static final short MODIFICATION = 1;
    public static final short ADDITION = 2;
    public static final short REMOVAL = 3;
    public Object getRelatedNode();
    public String getPrevValue();
    public String getNewValue();
    public String getAttrName();
    public short getAttrChange();
    public void initMutationEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Object relatedNodeArg, String prevValueArg, String newValueArg, String attrNameArg, short attrChangeArg);
}
