// Generated by esidl 0.4.0.

package org.w3c.dom.events;

import org.w3c.dom.html.Window;

public interface UIEvent extends Event
{
    // UIEvent
    public Window getView();
    public int getDetail();
    public void initUIEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Window viewArg, int detailArg);
}
