
var Gdx = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Gdx = {})  {

var b;b||(b=typeof Gdx !== 'undefined' ? Gdx : {});var h,l;b.ready=new Promise(function(a,c){h=a;l=c});var m=Object.assign({},b),n="object"==typeof window,q="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",v,w,x;
if(r){var fs=require("fs"),y=require("path");t=q?y.dirname(t)+"/":__dirname+"/";v=(a,c)=>{a=a.startsWith("file://")?new URL(a):y.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")};x=a=>{a=v(a,!0);a.buffer||(a=new Uint8Array(a));return a};w=(a,c,d)=>{a=a.startsWith("file://")?new URL(a):y.normalize(a);fs.readFile(a,function(e,f){e?d(e):c(f.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});if(15>process.version.match(/^v(\d+)\./)[1])process.on("unhandledRejection",
function(a){throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(n||q)q?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):t="",v=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},q&&(x=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),
w=(a,c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};b.print||console.log.bind(console);var z=b.printErr||console.warn.bind(console);Object.assign(b,m);m=null;var B;b.wasmBinary&&(B=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!=typeof WebAssembly&&C("no native wasm support detected");var D,E=!1,F="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,c){if(a){var d=H,e=a+c;for(c=a;d[c]&&!(c>=e);)++c;if(16<c-a&&d.buffer&&F)a=F.decode(d.subarray(a,c));else{for(e="";a<c;){var f=d[a++];if(f&128){var g=d[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=d[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|d[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a}var H,I=[],J=[],K=[];
function aa(){var a=b.preRun.shift();I.unshift(a)}var L=0,M=null,N=null;function C(a){if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";z(a);E=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");l(a);throw a;}function O(){return P.startsWith("data:application/octet-stream;base64,")}var P;P="gdx.wasm.wasm";if(!O()){var Q=P;P=b.locateFile?b.locateFile(Q,t):t+Q}
function R(){var a=P;try{if(a==P&&B)return new Uint8Array(B);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}catch(c){C(c)}}
function ba(){if(!B&&(n||q)){if("function"==typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return R()});if(w)return new Promise(function(a,c){w(P,function(d){a(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return R()})}function S(a){for(;0<a.length;)a.shift()(b)}var ca={a:function(){C("OOM")}};
(function(){function a(f){b.asm=f.exports;D=b.asm.b;f=D.buffer;b.HEAP8=new Int8Array(f);b.HEAP16=new Int16Array(f);b.HEAP32=new Int32Array(f);b.HEAPU8=H=new Uint8Array(f);b.HEAPU16=new Uint16Array(f);b.HEAPU32=new Uint32Array(f);b.HEAPF32=new Float32Array(f);b.HEAPF64=new Float64Array(f);J.unshift(b.asm.c);L--;b.monitorRunDependencies&&b.monitorRunDependencies(L);0==L&&(null!==M&&(clearInterval(M),M=null),N&&(f=N,N=null,f()))}function c(f){a(f.instance)}function d(f){return ba().then(function(g){return WebAssembly.instantiate(g,
e)}).then(function(g){return g}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);C(g)})}var e={a:ca};L++;b.monitorRunDependencies&&b.monitorRunDependencies(L);if(b.instantiateWasm)try{return b.instantiateWasm(e,a)}catch(f){z("Module.instantiateWasm callback failed with error: "+f),l(f)}(function(){return B||"function"!=typeof WebAssembly.instantiateStreaming||O()||P.startsWith("file://")||r||"function"!=typeof fetch?d(c):fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
e).then(c,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(l);return{}})();
var da=b._emscripten_bind_VoidPtr___destroy___0=function(){return(da=b._emscripten_bind_VoidPtr___destroy___0=b.asm.d).apply(null,arguments)},ea=b._emscripten_bind_gdx2d_pixmap___destroy___0=function(){return(ea=b._emscripten_bind_gdx2d_pixmap___destroy___0=b.asm.e).apply(null,arguments)},fa=b._emscripten_bind_Gdx_gdx2d_load_2=function(){return(fa=b._emscripten_bind_Gdx_gdx2d_load_2=b.asm.f).apply(null,arguments)},ha=b._emscripten_bind_Gdx_gdx2d_new_3=function(){return(ha=b._emscripten_bind_Gdx_gdx2d_new_3=
b.asm.g).apply(null,arguments)},ia=b._emscripten_bind_Gdx_gdx2d_free_1=function(){return(ia=b._emscripten_bind_Gdx_gdx2d_free_1=b.asm.h).apply(null,arguments)},ja=b._emscripten_bind_Gdx_gdx2d_set_blend_2=function(){return(ja=b._emscripten_bind_Gdx_gdx2d_set_blend_2=b.asm.i).apply(null,arguments)},ka=b._emscripten_bind_Gdx_gdx2d_set_scale_2=function(){return(ka=b._emscripten_bind_Gdx_gdx2d_set_scale_2=b.asm.j).apply(null,arguments)},la=b._emscripten_bind_Gdx_gdx2d_get_failure_reason_0=function(){return(la=
b._emscripten_bind_Gdx_gdx2d_get_failure_reason_0=b.asm.k).apply(null,arguments)},ma=b._emscripten_bind_Gdx_gdx2d_clear_2=function(){return(ma=b._emscripten_bind_Gdx_gdx2d_clear_2=b.asm.l).apply(null,arguments)},na=b._emscripten_bind_Gdx_gdx2d_set_pixel_4=function(){return(na=b._emscripten_bind_Gdx_gdx2d_set_pixel_4=b.asm.m).apply(null,arguments)},oa=b._emscripten_bind_Gdx_gdx2d_get_pixel_3=function(){return(oa=b._emscripten_bind_Gdx_gdx2d_get_pixel_3=b.asm.n).apply(null,arguments)},pa=b._emscripten_bind_Gdx_gdx2d_draw_line_6=
function(){return(pa=b._emscripten_bind_Gdx_gdx2d_draw_line_6=b.asm.o).apply(null,arguments)},qa=b._emscripten_bind_Gdx_gdx2d_draw_rect_6=function(){return(qa=b._emscripten_bind_Gdx_gdx2d_draw_rect_6=b.asm.p).apply(null,arguments)},ra=b._emscripten_bind_Gdx_gdx2d_draw_circle_5=function(){return(ra=b._emscripten_bind_Gdx_gdx2d_draw_circle_5=b.asm.q).apply(null,arguments)},sa=b._emscripten_bind_Gdx_gdx2d_fill_rect_6=function(){return(sa=b._emscripten_bind_Gdx_gdx2d_fill_rect_6=b.asm.r).apply(null,arguments)},
ta=b._emscripten_bind_Gdx_gdx2d_fill_circle_5=function(){return(ta=b._emscripten_bind_Gdx_gdx2d_fill_circle_5=b.asm.s).apply(null,arguments)},ua=b._emscripten_bind_Gdx_gdx2d_fill_triangle_8=function(){return(ua=b._emscripten_bind_Gdx_gdx2d_fill_triangle_8=b.asm.t).apply(null,arguments)},va=b._emscripten_bind_Gdx_gdx2d_draw_pixmap_10=function(){return(va=b._emscripten_bind_Gdx_gdx2d_draw_pixmap_10=b.asm.u).apply(null,arguments)},wa=b._emscripten_bind_Gdx_gdx2d_bytes_per_pixel_1=function(){return(wa=
b._emscripten_bind_Gdx_gdx2d_bytes_per_pixel_1=b.asm.v).apply(null,arguments)},xa=b._emscripten_bind_Gdx___destroy___0=function(){return(xa=b._emscripten_bind_Gdx___destroy___0=b.asm.w).apply(null,arguments)};b._malloc=function(){return(b._malloc=b.asm.y).apply(null,arguments)};b._free=function(){return(b._free=b.asm.z).apply(null,arguments)};b.___start_em_js=1048;b.___stop_em_js=1146;b.UTF8ToString=G;var T;N=function ya(){T||za();T||(N=ya)};
function za(){function a(){if(!T&&(T=!0,b.calledRun=!0,!E)){S(J);h(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();K.unshift(c)}S(K)}}if(!(0<L)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)aa();S(I);0<L||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();za();function U(){}U.prototype=Object.create(U.prototype);U.prototype.constructor=U;U.prototype.B=U;U.C={};b.WrapperObject=U;function V(a){return(a||U).C}b.getCache=V;function W(a,c){var d=V(c),e=d[a];if(e)return e;e=Object.create((c||U).prototype);e.A=a;return d[a]=e}b.wrapPointer=W;b.castObject=function(a,c){return W(a.A,c)};b.NULL=W(0);
b.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete V(a.B)[a.A]};b.compare=function(a,c){return a.A===c.A};b.getPointer=function(a){return a.A};b.getClass=function(a){return a.B};function X(){throw"cannot construct a VoidPtr, no constructor in IDL";}X.prototype=Object.create(U.prototype);X.prototype.constructor=X;X.prototype.B=X;X.C={};b.VoidPtr=X;X.prototype.__destroy__=function(){da(this.A)};
function Y(){throw"cannot construct a gdx2d_pixmap, no constructor in IDL";}Y.prototype=Object.create(U.prototype);Y.prototype.constructor=Y;Y.prototype.B=Y;Y.C={};b.gdx2d_pixmap=Y;Y.prototype.__destroy__=function(){ea(this.A)};function Z(){throw"cannot construct a Gdx, no constructor in IDL";}Z.prototype=Object.create(U.prototype);Z.prototype.constructor=Z;Z.prototype.B=Z;Z.C={};b.Gdx=Z;
Z.prototype.gdx2d_load=function(a,c){var d=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);return W(fa(d,a,c),Y)};Z.prototype.gdx2d_new=function(a,c,d){var e=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);return W(ha(e,a,c,d),Y)};Z.prototype.gdx2d_free=function(a){var c=this.A;a&&"object"===typeof a&&(a=a.A);ia(c,a)};
Z.prototype.gdx2d_set_blend=function(a,c){var d=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);ja(d,a,c)};Z.prototype.gdx2d_set_scale=function(a,c){var d=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);ka(d,a,c)};Z.prototype.gdx2d_get_failure_reason=function(){return G(la(this.A))};Z.prototype.gdx2d_clear=function(a,c){var d=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);ma(d,a,c)};
Z.prototype.gdx2d_set_pixel=function(a,c,d,e){var f=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);na(f,a,c,d,e)};Z.prototype.gdx2d_get_pixel=function(a,c,d){var e=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);return oa(e,a,c,d)};
Z.prototype.gdx2d_draw_line=function(a,c,d,e,f,g){var k=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);g&&"object"===typeof g&&(g=g.A);pa(k,a,c,d,e,f,g)};
Z.prototype.gdx2d_draw_rect=function(a,c,d,e,f,g){var k=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);g&&"object"===typeof g&&(g=g.A);qa(k,a,c,d,e,f,g)};
Z.prototype.gdx2d_draw_circle=function(a,c,d,e,f){var g=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);ra(g,a,c,d,e,f)};
Z.prototype.gdx2d_fill_rect=function(a,c,d,e,f,g){var k=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);g&&"object"===typeof g&&(g=g.A);sa(k,a,c,d,e,f,g)};
Z.prototype.gdx2d_fill_circle=function(a,c,d,e,f){var g=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);ta(g,a,c,d,e,f)};
Z.prototype.gdx2d_fill_triangle=function(a,c,d,e,f,g,k,p){var u=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);g&&"object"===typeof g&&(g=g.A);k&&"object"===typeof k&&(k=k.A);p&&"object"===typeof p&&(p=p.A);ua(u,a,c,d,e,f,g,k,p)};
Z.prototype.gdx2d_draw_pixmap=function(a,c,d,e,f,g,k,p,u,A){var Aa=this.A;a&&"object"===typeof a&&(a=a.A);c&&"object"===typeof c&&(c=c.A);d&&"object"===typeof d&&(d=d.A);e&&"object"===typeof e&&(e=e.A);f&&"object"===typeof f&&(f=f.A);g&&"object"===typeof g&&(g=g.A);k&&"object"===typeof k&&(k=k.A);p&&"object"===typeof p&&(p=p.A);u&&"object"===typeof u&&(u=u.A);A&&"object"===typeof A&&(A=A.A);va(Aa,a,c,d,e,f,g,k,p,u,A)};
Z.prototype.gdx2d_bytes_per_pixel=function(a){var c=this.A;a&&"object"===typeof a&&(a=a.A);return wa(c,a)};Z.prototype.__destroy__=function(){xa(this.A)};


  return Gdx.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Gdx;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Gdx; });
else if (typeof exports === 'object')
  exports["Gdx"] = Gdx;
async function asyncCall() {
	window.Gdx = await Gdx();
}

asyncCall();