
var Gdx = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Gdx = {})  {

var b;b||(b=typeof Gdx !== 'undefined' ? Gdx : {});var h,k;b.ready=new Promise(function(a,c){h=a;k=c});var n=Object.assign({},b),p="object"==typeof window,q="function"==typeof importScripts,t="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,u="",v,w,x;
if(t){var fs=require("fs"),y=require("path");u=q?y.dirname(u)+"/":__dirname+"/";v=(a,c)=>{a=a.startsWith("file://")?new URL(a):y.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")};x=a=>{a=v(a,!0);a.buffer||(a=new Uint8Array(a));return a};w=(a,c,d)=>{a=a.startsWith("file://")?new URL(a):y.normalize(a);fs.readFile(a,function(e,f){e?d(e):c(f.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});if(15>process.version.match(/^v(\d+)\./)[1])process.on("unhandledRejection",
function(a){throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(p||q)q?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):u="",v=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},q&&(x=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),
w=(a,c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};b.print||console.log.bind(console);var z=b.printErr||console.warn.bind(console);Object.assign(b,n);n=null;var B;b.wasmBinary&&(B=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!=typeof WebAssembly&&C("no native wasm support detected");var D,E=!1,F="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,c){if(a){var d=H,e=a+c;for(c=a;d[c]&&!(c>=e);)++c;if(16<c-a&&d.buffer&&F)a=F.decode(d.subarray(a,c));else{for(e="";a<c;){var f=d[a++];if(f&128){var g=d[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var l=d[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|d[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a}var I,H;
function J(){var a=D.buffer;b.HEAP8=I=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=new Int32Array(a);b.HEAPU8=H=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var K=[],L=[],M=[];function aa(){var a=b.preRun.shift();K.unshift(a)}var N=0,O=null,P=null;
function C(a){if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";z(a);E=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");k(a);throw a;}function Q(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="gdx.wasm.wasm";if(!Q()){var ba=R;R=b.locateFile?b.locateFile(ba,u):u+ba}function ca(){var a=R;try{if(a==R&&B)return new Uint8Array(B);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}catch(c){C(c)}}
function da(){if(!B&&(p||q)){if("function"==typeof fetch&&!R.startsWith("file://"))return fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return ca()});if(w)return new Promise(function(a,c){w(R,function(d){a(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return ca()})}function S(a){for(;0<a.length;)a.shift()(b)}
var ea={b:function(a,c,d){H.copyWithin(a,c,c+d)},a:function(a){var c=H.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);var f=Math,g=f.min;e=Math.max(a,e);e+=(65536-e%65536)%65536;a:{var l=D.buffer;try{D.grow(g.call(f,2147483648,e)-l.byteLength+65535>>>16);J();var m=1;break a}catch(r){}m=void 0}if(m)return!0}return!1}};
(function(){function a(f){b.asm=f.exports;D=b.asm.c;J();L.unshift(b.asm.d);N--;b.monitorRunDependencies&&b.monitorRunDependencies(N);0==N&&(null!==O&&(clearInterval(O),O=null),P&&(f=P,P=null,f()))}function c(f){a(f.instance)}function d(f){return da().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);C(g)})}var e={a:ea};N++;b.monitorRunDependencies&&b.monitorRunDependencies(N);if(b.instantiateWasm)try{return b.instantiateWasm(e,
a)}catch(f){z("Module.instantiateWasm callback failed with error: "+f),k(f)}(function(){return B||"function"!=typeof WebAssembly.instantiateStreaming||Q()||R.startsWith("file://")||t||"function"!=typeof fetch?d(c):fetch(R,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(c,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(k);return{}})();
var fa=b._emscripten_bind_VoidPtr___destroy___0=function(){return(fa=b._emscripten_bind_VoidPtr___destroy___0=b.asm.e).apply(null,arguments)},ha=b._emscripten_bind_gdx2d_pixmap_get_width_0=function(){return(ha=b._emscripten_bind_gdx2d_pixmap_get_width_0=b.asm.f).apply(null,arguments)},ia=b._emscripten_bind_gdx2d_pixmap_set_width_1=function(){return(ia=b._emscripten_bind_gdx2d_pixmap_set_width_1=b.asm.g).apply(null,arguments)},ja=b._emscripten_bind_gdx2d_pixmap_get_height_0=function(){return(ja=b._emscripten_bind_gdx2d_pixmap_get_height_0=
b.asm.h).apply(null,arguments)},ka=b._emscripten_bind_gdx2d_pixmap_set_height_1=function(){return(ka=b._emscripten_bind_gdx2d_pixmap_set_height_1=b.asm.i).apply(null,arguments)},la=b._emscripten_bind_gdx2d_pixmap_get_format_0=function(){return(la=b._emscripten_bind_gdx2d_pixmap_get_format_0=b.asm.j).apply(null,arguments)},ma=b._emscripten_bind_gdx2d_pixmap_set_format_1=function(){return(ma=b._emscripten_bind_gdx2d_pixmap_set_format_1=b.asm.k).apply(null,arguments)},na=b._emscripten_bind_gdx2d_pixmap_get_blend_0=
function(){return(na=b._emscripten_bind_gdx2d_pixmap_get_blend_0=b.asm.l).apply(null,arguments)},oa=b._emscripten_bind_gdx2d_pixmap_set_blend_1=function(){return(oa=b._emscripten_bind_gdx2d_pixmap_set_blend_1=b.asm.m).apply(null,arguments)},pa=b._emscripten_bind_gdx2d_pixmap_get_scale_0=function(){return(pa=b._emscripten_bind_gdx2d_pixmap_get_scale_0=b.asm.n).apply(null,arguments)},qa=b._emscripten_bind_gdx2d_pixmap_set_scale_1=function(){return(qa=b._emscripten_bind_gdx2d_pixmap_set_scale_1=b.asm.o).apply(null,
arguments)},ra=b._emscripten_bind_gdx2d_pixmap___destroy___0=function(){return(ra=b._emscripten_bind_gdx2d_pixmap___destroy___0=b.asm.p).apply(null,arguments)},sa=b._emscripten_bind_Gdx_g2d_get_pixels_1=function(){return(sa=b._emscripten_bind_Gdx_g2d_get_pixels_1=b.asm.q).apply(null,arguments)},ta=b._emscripten_bind_Gdx_g2d_load_3=function(){return(ta=b._emscripten_bind_Gdx_g2d_load_3=b.asm.r).apply(null,arguments)},ua=b._emscripten_bind_Gdx_g2d_new_3=function(){return(ua=b._emscripten_bind_Gdx_g2d_new_3=
b.asm.s).apply(null,arguments)},va=b._emscripten_bind_Gdx_g2d_free_1=function(){return(va=b._emscripten_bind_Gdx_g2d_free_1=b.asm.t).apply(null,arguments)},wa=b._emscripten_bind_Gdx_g2d_set_blend_2=function(){return(wa=b._emscripten_bind_Gdx_g2d_set_blend_2=b.asm.u).apply(null,arguments)},xa=b._emscripten_bind_Gdx_g2d_set_scale_2=function(){return(xa=b._emscripten_bind_Gdx_g2d_set_scale_2=b.asm.v).apply(null,arguments)},ya=b._emscripten_bind_Gdx_g2d_get_failure_reason_0=function(){return(ya=b._emscripten_bind_Gdx_g2d_get_failure_reason_0=
b.asm.w).apply(null,arguments)},za=b._emscripten_bind_Gdx_g2d_clear_2=function(){return(za=b._emscripten_bind_Gdx_g2d_clear_2=b.asm.x).apply(null,arguments)},Aa=b._emscripten_bind_Gdx_g2d_set_pixel_4=function(){return(Aa=b._emscripten_bind_Gdx_g2d_set_pixel_4=b.asm.y).apply(null,arguments)},Ba=b._emscripten_bind_Gdx_g2d_get_pixel_3=function(){return(Ba=b._emscripten_bind_Gdx_g2d_get_pixel_3=b.asm.z).apply(null,arguments)},Ca=b._emscripten_bind_Gdx_g2d_draw_line_6=function(){return(Ca=b._emscripten_bind_Gdx_g2d_draw_line_6=
b.asm.A).apply(null,arguments)},Da=b._emscripten_bind_Gdx_g2d_draw_rect_6=function(){return(Da=b._emscripten_bind_Gdx_g2d_draw_rect_6=b.asm.B).apply(null,arguments)},Ea=b._emscripten_bind_Gdx_g2d_draw_circle_5=function(){return(Ea=b._emscripten_bind_Gdx_g2d_draw_circle_5=b.asm.C).apply(null,arguments)},Fa=b._emscripten_bind_Gdx_g2d_fill_rect_6=function(){return(Fa=b._emscripten_bind_Gdx_g2d_fill_rect_6=b.asm.D).apply(null,arguments)},Ga=b._emscripten_bind_Gdx_g2d_fill_circle_5=function(){return(Ga=
b._emscripten_bind_Gdx_g2d_fill_circle_5=b.asm.E).apply(null,arguments)},Ha=b._emscripten_bind_Gdx_g2d_fill_triangle_8=function(){return(Ha=b._emscripten_bind_Gdx_g2d_fill_triangle_8=b.asm.F).apply(null,arguments)},Ia=b._emscripten_bind_Gdx_g2d_draw_pixmap_10=function(){return(Ia=b._emscripten_bind_Gdx_g2d_draw_pixmap_10=b.asm.G).apply(null,arguments)},Ja=b._emscripten_bind_Gdx_g2d_bytes_per_pixel_1=function(){return(Ja=b._emscripten_bind_Gdx_g2d_bytes_per_pixel_1=b.asm.H).apply(null,arguments)},
Ka=b._emscripten_bind_Gdx___destroy___0=function(){return(Ka=b._emscripten_bind_Gdx___destroy___0=b.asm.I).apply(null,arguments)};b._free=function(){return(b._free=b.asm.K).apply(null,arguments)};b._malloc=function(){return(b._malloc=b.asm.L).apply(null,arguments)};b.___start_em_js=9976;b.___stop_em_js=10074;b.UTF8ToString=G;b.writeArrayToMemory=function(a,c){I.set(a,c)};var T;P=function La(){T||Ma();T||(P=La)};
function Ma(){function a(){if(!T&&(T=!0,b.calledRun=!0,!E)){S(L);h(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();M.unshift(c)}S(M)}}if(!(0<N)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)aa();S(K);0<N||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();Ma();function U(){}U.prototype=Object.create(U.prototype);U.prototype.constructor=U;U.prototype.M=U;U.N={};b.WrapperObject=U;function V(a){return(a||U).N}b.getCache=V;function W(a,c){var d=V(c),e=d[a];if(e)return e;e=Object.create((c||U).prototype);e.J=a;return d[a]=e}b.wrapPointer=W;b.castObject=function(a,c){return W(a.J,c)};b.NULL=W(0);
b.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete V(a.M)[a.J]};b.compare=function(a,c){return a.J===c.J};b.getPointer=function(a){return a.J};b.getClass=function(a){return a.M};function X(){throw"cannot construct a VoidPtr, no constructor in IDL";}X.prototype=Object.create(U.prototype);X.prototype.constructor=X;X.prototype.M=X;X.N={};b.VoidPtr=X;X.prototype.__destroy__=function(){fa(this.J)};
function Y(){throw"cannot construct a gdx2d_pixmap, no constructor in IDL";}Y.prototype=Object.create(U.prototype);Y.prototype.constructor=Y;Y.prototype.M=Y;Y.N={};b.gdx2d_pixmap=Y;Y.prototype.get_width=Y.prototype.T=function(){return ha(this.J)};Y.prototype.set_width=Y.prototype.Y=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);ia(c,a)};Object.defineProperty(Y.prototype,"width",{get:Y.prototype.T,set:Y.prototype.Y});Y.prototype.get_height=Y.prototype.R=function(){return ja(this.J)};
Y.prototype.set_height=Y.prototype.W=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);ka(c,a)};Object.defineProperty(Y.prototype,"height",{get:Y.prototype.R,set:Y.prototype.W});Y.prototype.get_format=Y.prototype.P=function(){return la(this.J)};Y.prototype.set_format=Y.prototype.V=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);ma(c,a)};Object.defineProperty(Y.prototype,"format",{get:Y.prototype.P,set:Y.prototype.V});Y.prototype.get_blend=Y.prototype.O=function(){return na(this.J)};
Y.prototype.set_blend=Y.prototype.U=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);oa(c,a)};Object.defineProperty(Y.prototype,"blend",{get:Y.prototype.O,set:Y.prototype.U});Y.prototype.get_scale=Y.prototype.S=function(){return pa(this.J)};Y.prototype.set_scale=Y.prototype.X=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);qa(c,a)};Object.defineProperty(Y.prototype,"scale",{get:Y.prototype.S,set:Y.prototype.X});Y.prototype.__destroy__=function(){ra(this.J)};
function Z(){throw"cannot construct a Gdx, no constructor in IDL";}Z.prototype=Object.create(U.prototype);Z.prototype.constructor=Z;Z.prototype.M=Z;Z.N={};b.Gdx=Z;Z.prototype.g2d_get_pixels=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);return sa(c,a)};Z.prototype.g2d_load=function(a,c,d){var e=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);return W(ta(e,a,c,d),Y)};
Z.prototype.g2d_new=function(a,c,d){var e=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);return W(ua(e,a,c,d),Y)};Z.prototype.g2d_free=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);va(c,a)};Z.prototype.g2d_set_blend=function(a,c){var d=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);wa(d,a,c)};
Z.prototype.g2d_set_scale=function(a,c){var d=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);xa(d,a,c)};Z.prototype.g2d_get_failure_reason=function(){return G(ya(this.J))};Z.prototype.g2d_clear=function(a,c){var d=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);za(d,a,c)};
Z.prototype.g2d_set_pixel=function(a,c,d,e){var f=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);Aa(f,a,c,d,e)};Z.prototype.g2d_get_pixel=function(a,c,d){var e=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);return Ba(e,a,c,d)};
Z.prototype.g2d_draw_line=function(a,c,d,e,f,g){var l=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);g&&"object"===typeof g&&(g=g.J);Ca(l,a,c,d,e,f,g)};
Z.prototype.g2d_draw_rect=function(a,c,d,e,f,g){var l=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);g&&"object"===typeof g&&(g=g.J);Da(l,a,c,d,e,f,g)};
Z.prototype.g2d_draw_circle=function(a,c,d,e,f){var g=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);Ea(g,a,c,d,e,f)};
Z.prototype.g2d_fill_rect=function(a,c,d,e,f,g){var l=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);g&&"object"===typeof g&&(g=g.J);Fa(l,a,c,d,e,f,g)};
Z.prototype.g2d_fill_circle=function(a,c,d,e,f){var g=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);Ga(g,a,c,d,e,f)};
Z.prototype.g2d_fill_triangle=function(a,c,d,e,f,g,l,m){var r=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);g&&"object"===typeof g&&(g=g.J);l&&"object"===typeof l&&(l=l.J);m&&"object"===typeof m&&(m=m.J);Ha(r,a,c,d,e,f,g,l,m)};
Z.prototype.g2d_draw_pixmap=function(a,c,d,e,f,g,l,m,r,A){var Na=this.J;a&&"object"===typeof a&&(a=a.J);c&&"object"===typeof c&&(c=c.J);d&&"object"===typeof d&&(d=d.J);e&&"object"===typeof e&&(e=e.J);f&&"object"===typeof f&&(f=f.J);g&&"object"===typeof g&&(g=g.J);l&&"object"===typeof l&&(l=l.J);m&&"object"===typeof m&&(m=m.J);r&&"object"===typeof r&&(r=r.J);A&&"object"===typeof A&&(A=A.J);Ia(Na,a,c,d,e,f,g,l,m,r,A)};
Z.prototype.g2d_bytes_per_pixel=function(a){var c=this.J;a&&"object"===typeof a&&(a=a.J);return Ja(c,a)};Z.prototype.__destroy__=function(){Ka(this.J)};


  return Gdx.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Gdx;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Gdx; });
else if (typeof exports === 'object')
  exports["Gdx"] = Gdx;
async function asyncCall() {
	window.Gdx = await Gdx();
}

asyncCall();