/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.math.Vector3;

/** @author xpenatan */
public class btBoxShape extends btPolyhedralConvexShape {

    public btBoxShape(Vector3 boxHalfExtents) {
        resetObj(createNative(boxHalfExtents.x, boxHalfExtents.y, boxHalfExtents.z), true);
    }

    public static long createNative(float x, float y, float z) {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var tmp=Bullet.MyTemp.prototype.btVec3();tmp.setValue(x,y,z);",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(new Bullet.btBoxShape(tmp));",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btBoxShape);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=Bullet.wrapPointer(addr,Bullet.btBoxShape);Bullet.destroy(vec);",this);
    }

    public void getHalfExtentsWithMargin(Vector3 out) {
		checkPointer();
		float x=0,y=0,z=0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=this.$$$jsObj.getHalfExtentsWithMargin();x=vec.x();y=vec.y();z=vec.z();",this);
		out.set(x,y,z);
    }

    public void getHalfExtentsWithoutMargin(Vector3 out) {
		checkPointer();
		float x=0,y=0,z=0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=this.$$$jsObj.getHalfExtentsWithoutMargin();x=vec.x();y=vec.y();z=vec.z();",this);
		out.set(x,y,z);
    }
}
