/*-------------------------------------------------------
 * This file was generated by XpeCodeGen
 * Version 1.0.0
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btBroadphasePairArray extends BulletBase {

    btBroadphasePair tmp = new btBroadphasePair(0, false);

    public btBroadphasePairArray(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.put("addr",this.cPointer,this);
		this.jsObj = com.dragome.commons.javascript.ScriptHelper.eval("Bullet.wrapPointer(addr,Bullet.btBroadphasePairArray);",this);
	}

    public int size() {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.put("jsObj",this.jsObj,this);
		return com.dragome.commons.javascript.ScriptHelper.evalInt("jsObj.size();",this);
    }

    /**
	 * Dont keep a reference of any object.
	 */
    public btBroadphasePair at(int n) {
		com.dragome.commons.javascript.ScriptHelper.put("n",n,this);
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.put("jsObj",this.jsObj,this);
		long addr = com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(jsObj.at(n))",this);
		tmp.resetObj(addr, false);
		return tmp;
    }

    public int capacity() {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.put("jsObj",this.jsObj,this);
		return com.dragome.commons.javascript.ScriptHelper.evalInt("jsObj.capacity();",this);
    }

    public void resize(int newsize) {
		com.dragome.commons.javascript.ScriptHelper.put("newsize",newsize,this);
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.put("jsObj",this.jsObj,this);
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("jsObj.resize(newsize);",this);
    }
    //	public int getCollisionObjects(int[] result, int max, int other) {
    //		return 0;
    //	}
    //	
    //	private static native void getCollisionObjects(long addr, int[] result, int max, int other); /*
    //		btBroadphasePairArray * array = (btBroadphasePairArray *)addr;
    //		
    //	*/
    //	/*[0;X;D]*/
    //
    //	public int getCollisionObjectsValue(int[] result, int max, int other) {
    //		return 0;
    //	}
}
