/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btBroadphasePairArray extends BulletBase {

    btBroadphasePair tmp = new btBroadphasePair(0, false);

    public btBroadphasePairArray(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btBroadphasePairArray);",this);
	}

    public int size() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.size();",this);
    }

    /**
	 * Dont keep a reference of any object.
	 */
    public btBroadphasePair at(int n) {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.at(n));",this);
		tmp.resetObj(addr, false);
		return tmp;
    }

    public int capacity() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.capacity();",this);
    }

    public void resize(int newsize) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.resize(newsize);",this);
    }
    //	public int getCollisionObjects(int[] result, int max, int other) {
    //		return 0;
    //	}
    //	
    //	private static native void getCollisionObjects(long addr, int[] result, int max, int other); /*
    //		btBroadphasePairArray * array = (btBroadphasePairArray *)addr;
    //		
    //	*/
    //	/*[0;X;D]*/
    //
    //	public int getCollisionObjectsValue(int[] result, int max, int other) {
    //		return 0;
    //	}
}
