/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btBroadphaseInterface extends BulletBase {

    btOverlappingPairCache overlappingPairCache = new btOverlappingPairCache(0, false);

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btBroadphaseInterface);",this);
	}

    public btOverlappingPairCache getOverlappingPairCache() {
		checkPointer();
		if(overlappingPairCache.cPointer == 0) {
			long addr = 0;
			com.dragome.commons.javascript.ScriptHelper.evalNoResult("var pairCache=this.$$$jsObj.getOverlappingPairCache();addr=Bullet.getPointer(pairCache);",this);
			overlappingPairCache.resetObj(addr,false);
		}
		return overlappingPairCache;
    }
}
