/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btBroadphasePair extends BulletBase {

    btCollisionAlgorithm tmp = new btCollisionAlgorithm(0, false);

    public btBroadphasePair(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btBroadphasePair);",this);
	}

    public btCollisionAlgorithm getAlgorithm() {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.get_m_algorithm());",this);
		if(addr == 0) return null;
		tmp.resetObj(addr, false);
		return tmp;
    }
}
