/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

/** @author xpenatan */
public class btCapsuleShape extends btConvexInternalShape {

    public btCapsuleShape(float radius, float height) {
        resetObj(createNative(radius, height), true);
    }

    public static long createNative(float radius, float height) {
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(new Bullet.btCapsuleShape(radius,height));",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btCapsuleShape);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var jsObj=Bullet.wrapPointer(addr,Bullet.btCapsuleShape);Bullet.destroy(jsObj);",this);
    }
}
