/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

/** @author xpenatan */
public class btCollisionDispatcher extends btDispatcher {

    public btCollisionDispatcher(btCollisionConfiguration collisionConfiguration) {
        resetObj(createNative(collisionConfiguration.cPointer), true);
    }

    private static long createNative(long collisionConfigurationAddr) {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var config=Bullet.wrapPointer(collisionConfigurationAddr,Bullet.btCollisionConfiguration);var disp=new Bullet.btCollisionDispatcher(config);",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(disp);",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btCollisionDispatcher);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var disp=Bullet.wrapPointer(addr,Bullet.btCollisionDispatcher);Bullet.destroy(disp);",this);
    }
}
