/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.math.Matrix4;
import com.badlogic.gdx.utils.Array;

/** @author xpenatan */
public class btCompoundShape extends btCollisionShape {

    protected Array<btCollisionShape> children = new Array<btCollisionShape>();

    public btCompoundShape() {
        resetObj(createNative(), true);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btCompoundShape);",this);
	}

    public static long createNative() {
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(new Bullet.btCompoundShape());",null);
    }

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=Bullet.wrapPointer(addr,Bullet.btCompoundShape);Bullet.destroy(vec);",this);
		children.clear();
    }

    public void addChildShape(Matrix4 localTransform, btCollisionShape shape) {
		checkPointer();
		float [] value = localTransform.val;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var tran=Bullet.MyTemp.prototype.btTran();tran.setFromOpenGLMatrix(value);this.$$$jsObj.addChildShape(tran,shape.$$$jsObj);",this);
		children.add(shape);
    }

    public void removeChildShape(btCollisionShape shape) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.removeChildShape(shape.$$$jsObj);",this);
		children.removeValue(shape, true);
    }

    public int getNumChildShapes() {
        return children.size;
    }

    public btCollisionShape getChildShape(int index) {
        return children.get(index);
    }
}
