/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.math.Vector3;

/** @author xpenatan */
public class btCylinderShape extends btConvexInternalShape {

    public btCylinderShape(Vector3 halfExtents) {
        resetObj(createNative(halfExtents.x, halfExtents.y, halfExtents.z), true);
    }

    public static long createNative(float x, float y, float z) {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=Bullet.Temp.prototype.btVec3();vec.setValue(x,y,z);",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(new Bullet.btCylinderShape(vec));",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btCylinderShape);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=Bullet.wrapPointer(addr,Bullet.btCylinderShape);Bullet.destroy(vec);",this);
    }
}
