/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

/** @author xpenatan */
public class btDbvtBroadphase extends btBroadphaseInterface {

    public btDbvtBroadphase() {
        resetObj(createNative(), true);
    }

    private static long createNative() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var dbvt=new Bullet.btDbvtBroadphase();",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(dbvt);",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btDbvtBroadphase);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var dbvt=Bullet.wrapPointer(addr,Bullet.btDbvtBroadphase);Bullet.destroy(dbvt);",this);
    }
}
