/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btDispatcher extends BulletBase {

    private btPersistentManifold manifold = new btPersistentManifold(0, false);

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btDispatcher);",this);
	}

    public int getNumManifolds() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.getNumManifolds();",this);
    }

    public btPersistentManifold getManifoldByIndexInternal(int index) {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.getManifoldByIndexInternal(index));",this);
		manifold.resetObj(addr, false);
		return manifold;
    }
}
