/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

/** @author xpenatan */
public class btOverlappingPairCache extends btOverlappingPairCallback {

    btBroadphasePairArray tmp = new btBroadphasePairArray(0, false);

    public btOverlappingPairCache(long cPtr, boolean cMemoryOwn) {
        super(cPtr, cMemoryOwn);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btOverlappingPairCache);",this);
	}

    public btBroadphasePairArray getOverlappingPairArray() {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.getOverlappingPairArray());",this);
		tmp.resetObj(addr, false);
		return tmp;
    }
}
