/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.linearmath.btTypedObject;

/** @author xpenatan */
public class btPersistentManifold extends btTypedObject {

    private btManifoldPoint maniFoldPoint = new btManifoldPoint(0, false);

    public btPersistentManifold(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btPersistentManifold);",this);
	}

    public btManifoldPoint getContactPoint(int index) {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.getContactPoint(index));",this);
		maniFoldPoint.resetObj(addr, false);
		return maniFoldPoint;
    }

    public int getNumContacts() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.getNumContacts();",this);
    }

    public btCollisionObject getBody0(btCollisionWorld world) {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.getBody0());",this);
		return world.bodies.get(addr);
    }

    public btCollisionObject getBody1(btCollisionWorld world) {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.getBody1());",this);
		return world.bodies.get(addr);
    }
}
