/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.btVector3;

/** @author xpenatan */
public class btShapeHull extends BulletBase {

    public btShapeHull(btConvexShape shape) {
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btShapeHull);",this);
	}

    public boolean buildHull(float margin) {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalBoolean("this.$$$jsObj.buildHull(margin);",this);
    }

    public int numTriangles() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.numTriangles();",this);
    }

    public int numVertices() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.numVertices();",this);
    }

    public int numIndices() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalInt("this.$$$jsObj.numIndices();",this);
    }

    public btVector3[] getVertexPointer() {
        throw new RuntimeException("getVertexPointer not implemented");
    }

    public java.nio.LongBuffer getIndexPointer() {
        throw new RuntimeException("getIndexPointer not implemented");
    }
}
