/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class LocalRayResult extends BulletBase {

    private LocalShapeInfo localShapeInfo = new LocalShapeInfo(0, false);

    public LocalRayResult(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.LocalRayResult);",this);
	}

    public LocalShapeInfo getLocalShapeInfo() {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.get_m_localShapeInfo());",this);
		if(addr != 0) {
			localShapeInfo.resetObj(addr, false);
			return localShapeInfo;
		}
		return null;
    }

    public btCollisionObject getCollisionObject(btCollisionWorld world) {
		checkPointer();
		long addr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("addr=Bullet.getPointer(this.$$$jsObj.get_m_collisionObject());",this);
		return world.bodies.get(addr);
    }
}
