/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class RayResultCallback extends BulletBase {

    static LocalRayResult tmpLocalRes = new LocalRayResult(0, false);

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.RayResultCallback);",this);
	}

    @Override
    protected void delete() {
        clear();
    }

    public boolean hasHit() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalBoolean("this.$$$jsObj.hasHit();",this);
    }

    public void setClosestHitFraction(float value) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.set_m_closestHitFraction(value);",this);
    }

    public void setCollisionObject(btCollisionObject value) {
		checkPointer();
		long coladdr = value != null ? value.cPointer : 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var colobj=Bullet.wrapPointer(coladdr,Bullet.btCollisionObject);this.$$$jsObj.set_m_collisionObject(colobj);",this);
    }

    public btCollisionObject getCollisionObject(btCollisionWorld world) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var collObj=this.$$$jsObj.get_m_collisionObject();",this);
		long colAddr = 0;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("if(collObj !==undefined) {var pointer=Bullet.getPointer(collObj);if(pointer !==undefined)colAddr=pointer;}",this);
		return world.bodies.get(colAddr);
    }

    public float addSingleResult(LocalRayResult rayResult, boolean normalInWorldSpace) {
        return 0;
    }

    /**
	 * Use to remove objects after raycasting
	 */
    public void clear() {
        setCollisionObject(null);
    }
    //TODO need to finish
}
