
interface b2World {
    void b2World([Const, Ref]b2Vec2 gravity);
    void Step(float timeStep, long velocityIterations, long positionIterations);
    [Value]b2Vec2 GetGravity();
};

interface b2Vec2 {
    attribute float x;
    attribute float y;
    void b2Vec2();
    void b2Vec2(float x, float y);
    void SetZero();
    void Set(float x, float y);
    float Length();
    float LengthSquared();
    float Normalize();
    boolean IsValid();
};
