// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

public interface ArrayBufferView
{
    // ArrayBufferView
    public ArrayBuffer getBuffer();
    public int getByteOffset();
    public int getByteLength();
}
