// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

public interface DataView extends ArrayBufferView
{
    // DataView
    public byte getInt8(int byteOffset);
    public byte getUint8(int byteOffset);
    public short getInt16(int byteOffset);
    public short getInt16(int byteOffset, boolean littleEndian);
    public short getUint16(int byteOffset);
    public short getUint16(int byteOffset, boolean littleEndian);
    public int getInt32(int byteOffset);
    public int getInt32(int byteOffset, boolean littleEndian);
    public int getUint32(int byteOffset);
    public int getUint32(int byteOffset, boolean littleEndian);
    public float getFloat32(int byteOffset);
    public float getFloat32(int byteOffset, boolean littleEndian);
    public double getFloat64(int byteOffset);
    public double getFloat64(int byteOffset, boolean littleEndian);
    public void setInt8(int byteOffset, byte value);
    public void setUint8(int byteOffset, byte value);
    public void setInt16(int byteOffset, short value);
    public void setInt16(int byteOffset, short value, boolean littleEndian);
    public void setUint16(int byteOffset, short value);
    public void setUint16(int byteOffset, short value, boolean littleEndian);
    public void setInt32(int byteOffset, int value);
    public void setInt32(int byteOffset, int value, boolean littleEndian);
    public void setUint32(int byteOffset, int value);
    public void setUint32(int byteOffset, int value, boolean littleEndian);
    public void setFloat32(int byteOffset, float value);
    public void setFloat32(int byteOffset, float value, boolean littleEndian);
    public void setFloat64(int byteOffset, double value);
    public void setFloat64(int byteOffset, double value, boolean littleEndian);
}
