// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.FloatArray;

public interface Float32Array extends ArrayBufferView
{
    // Float32Array
    public static final int BYTES_PER_ELEMENT = 4;
    public int getLength();
    public float get(int index);
    public void set(int index, float value);
    public void set(Float32Array array);
    public void set(Float32Array array, int offset);
    public void set(FloatArray array);
    public void set(FloatArray array, int offset);
    public Float32Array subarray(int start, int end);
}
