// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.FloatArray;

public interface Float32Array_Constructor
{
    // Constructor
    public Float32Array createInstance(int length);
    public Float32Array createInstance(ArrayBufferView array);
    public Float32Array createInstance(FloatArray array);
    public Float32Array createInstance(ArrayBuffer buffer);
    public Float32Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Float32Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
