// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.DoubleArray;

public interface Float64Array_Constructor
{
    // Constructor
    public Float64Array createInstance(int length);
    public Float64Array createInstance(ArrayBufferView array);
    public Float64Array createInstance(DoubleArray array);
    public Float64Array createInstance(ArrayBuffer buffer);
    public Float64Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Float64Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
