// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.DoubleArray;

public interface Float64Array extends ArrayBufferView
{
    // Float64Array
    public static final int BYTES_PER_ELEMENT = 8;
    public int getLength();
    public double get(int index);
    public void set(int index, double value);
    public void set(Float64Array array);
    public void set(Float64Array array, int offset);
    public void set(DoubleArray array);
    public void set(DoubleArray array, int offset);
    public Float64Array subarray(int start, int end);
}
