// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.ShortArray;

public interface Int16Array_Constructor
{
    // Constructor
    public Int16Array createInstance(int length);
    public Int16Array createInstance(ArrayBufferView array);
    public Int16Array createInstance(ShortArray array);
    public Int16Array createInstance(ArrayBuffer buffer);
    public Int16Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Int16Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
