// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.ShortArray;

public interface Int16Array extends ArrayBufferView
{
    // Int16Array
    public static final int BYTES_PER_ELEMENT = 2;
    public int getLength();
    public short get(int index);
    public void set(int index, short value);
    public void set(Int16Array array);
    public void set(Int16Array array, int offset);
    public void set(ShortArray array);
    public void set(ShortArray array, int offset);
    public Int16Array subarray(int start, int end);
}
