// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.LongArray;

public interface Int32Array_Constructor
{
    // Constructor
    public Int32Array createInstance(int length);
    public Int32Array createInstance(ArrayBufferView array);
    public Int32Array createInstance(LongArray array);
    public Int32Array createInstance(ArrayBuffer buffer);
    public Int32Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Int32Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
