// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.ByteArray;

public interface Int8Array_Constructor
{
    // Constructor
    public Int8Array createInstance(int length);
    public Int8Array createInstance(ArrayBufferView array);
    public Int8Array createInstance(ByteArray array);
    public Int8Array createInstance(ArrayBuffer buffer);
    public Int8Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Int8Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
