// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.OctetArray;

public interface Uint8Array_Constructor
{
    // Constructor
    public Uint8Array createInstance(int length);
    public Uint8Array createInstance(ArrayBufferView array);
    public Uint8Array createInstance(OctetArray array);
    public Uint8Array createInstance(ArrayBuffer buffer);
    public Uint8Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Uint8Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
