// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.UnsignedShortArray;

public interface Uint16Array_Constructor
{
    // Constructor
    public Uint16Array createInstance(int length);
    public Uint16Array createInstance(ArrayBufferView array);
    public Uint16Array createInstance(UnsignedShortArray array);
    public Uint16Array createInstance(ArrayBuffer buffer);
    public Uint16Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Uint16Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
