// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.UnsignedShortArray;

public interface Uint16Array extends ArrayBufferView
{
    // Uint16Array
    public static final int BYTES_PER_ELEMENT = 2;
    public int getLength();
    public short get(int index);
    public void set(int index, short value);
    public void set(Uint16Array array);
    public void set(Uint16Array array, int offset);
    public void set(UnsignedShortArray array);
    public void set(UnsignedShortArray array, int offset);
    public Uint16Array subarray(int start, int end);
}
