// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.UnsignedLongArray;

public interface Uint32Array_Constructor
{
    // Constructor
    public Uint32Array createInstance(int length);
    public Uint32Array createInstance(ArrayBufferView array);
    public Uint32Array createInstance(UnsignedLongArray array);
    public Uint32Array createInstance(ArrayBuffer buffer);
    public Uint32Array createInstance(ArrayBuffer buffer, int byteOffset);
    public Uint32Array createInstance(ArrayBuffer buffer, int byteOffset, int length);
}
