// Generated by esidl 0.4.0.

package org.w3c.dom.typedarray;

import org.w3c.dom.OctetArray;

public interface Uint8Array extends ArrayBufferView
{
    // Uint8Array
    public static final int BYTES_PER_ELEMENT = 1;
    public int getLength();
    public byte get(int index);
    public void set(int index, byte value);
    public void set(Uint8Array array);
    public void set(Uint8Array array, int offset);
    public void set(OctetArray array);
    public void set(OctetArray array, int offset);
    public Uint8Array subarray(int start, int end);
}
