/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.linearmath;

import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btQuaternion extends BulletBase {

    public static final float[] localArr_1 = new float[4];

    public static final float[] localArr_2 = new float[4];

    public btQuaternion() {
        resetObj(createNative(0, 0, 0, 0), true);
    }

    public btQuaternion(float x, float y, float z, float w) {
        resetObj(createNative(x, y, z, w), true);
    }

    public btQuaternion(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

    private static long createNative(float x, float y, float z, float w) {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var quat=new Bullet.btQuaternion(x,y,z,w);",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(quat);",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btQuaternion);",this);
	}

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var quat=Bullet.wrapPointer(addr,Bullet.btTransform);Bullet.destroy(quat);",this);
    }

    public static void set(btQuaternion quat, float[] value) {
		quat.checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setValue(value[0],value[1],value[2],value[3]);",null);
    }

    public static void get(btQuaternion quaternion, float[] value) {
		quaternion.checkPointer();
		Object quat = quaternion.jsObj;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("value[0]=quat.x();value[1]=quat.y();value[2]=quat.z();value[3]=quat.w();",null);
    }

    public static void set(Quaternion in, btQuaternion out) {
		out.checkPointer();
		btQuaternion.localArr_1[0] = in.x;
		btQuaternion.localArr_1[1] = in.y;
		btQuaternion.localArr_1[2] = in.z;
		btQuaternion.localArr_1[3] = in.w;
		btQuaternion.set(out, btQuaternion.localArr_1);
    }

    public static void get(btQuaternion in, Quaternion out) {
		in.checkPointer();
		btQuaternion.get(in, btQuaternion.localArr_1);
		out.set(btQuaternion.localArr_1[0], btQuaternion.localArr_1[1], btQuaternion.localArr_1[2],btQuaternion.localArr_1[3]);
    }

    public void setValue(float x, float y, float z, float w) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setValue(x,y,z,w);",this);
    }

    public float getX() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.x();",this);
    }

    public float getY() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.y();",this);
    }

    public float getZ() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.z();",this);
    }

    public float getW() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.w();",this);
    }

    public void setX(float x) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setX(x);",this);
    }

    public void setY(float y) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setY(y);",this);
    }

    public void setZ(float z) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setZ(z);",this);
    }

    public void setW(float w) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setW(w);",this);
    }
}
