/*-------------------------------------------------------
 * This file was generated by XpeCodeGen
 * Version 1.0.0
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.linearmath;

/** @author xpenatan */
public class btScalar {

    public static int btGetVersion() {
		return com.dragome.commons.javascript.ScriptHelper.evalInt("Bullet.MyClassHelper.prototype.getBTVersion();",null);
    }
}
