/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.linearmath;

/** @author xpenatan */
public class btScalar {

    public static int btGetVersion() {
		return com.dragome.commons.javascript.ScriptHelper.evalInt("Bullet.MyClassHelper.prototype.getBTVersion();",null);
    }
}
