/*-------------------------------------------------------
 * This file was automatically generated by XpeCodeGen
 *
 * Dont make changes to this file
 *-------------------------------------------------------*/
package com.badlogic.gdx.physics.bullet.linearmath;

import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.physics.bullet.BulletBase;

/** @author xpenatan */
public class btVector3 extends BulletBase {

    public static final Vector3 vector3_1 = new Vector3();

    public static final Vector3 vector3_2 = new Vector3();

    public static final Vector3 vector3_3 = new Vector3();

    public static final float[] localArr_1 = new float[3];

    public static final float[] localArr_2 = new float[3];

	final public static btVector3 btVector3_1 = new btVector3(); // Pointer
	final public static btVector3 btVector3_2 = new btVector3(); // Pointer

    public btVector3() {
        create();
    }

    public btVector3(float x, float y, float z) {
        resetObj(createNative(x, y, z), true);
    }

    public btVector3(long cPtr, boolean cMemoryOwn) {
        resetObj(cPtr, cMemoryOwn);
    }

    protected void create() {
        resetObj(createNative(0, 0, 0), true);
    }

    @Override
    protected void delete() {
		long addr = cPointer;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=Bullet.wrapPointer(addr,Bullet.btVector3);Bullet.destroy(vec);",this);
    }

    private static long createNative(float x, float y, float z) {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("var vec=new Bullet.btVector3(x,y,z);",null);
		return com.dragome.commons.javascript.ScriptHelper.evalLong("Bullet.getPointer(vec);",null);
    }

	protected void cacheObj() {
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj=Bullet.wrapPointer(this.$$$cPointer,Bullet.btVector3);",this);
	}

    public void setValue(float x, float y, float z) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setValue(x,y,z);",this);
    }

    public float getX() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.x();",this);
    }

    public float getY() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.y();",this);
    }

    public float getZ() {
		checkPointer();
		return com.dragome.commons.javascript.ScriptHelper.evalFloat("this.$$$jsObj.z();",this);
    }

    public void setX(float x) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setX(x);",this);
    }

    public void setY(float y) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setY(y);",this);
    }

    public void setZ(float z) {
		checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setZ(z);",this);
    }

    public static void set(btVector3 vec, float[] value) {
		vec.checkPointer();
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("this.$$$jsObj.setValue(value[0],value[1],value[2]);",null);
    }

    public static void get(btVector3 vector, float[] value) {
		vector.checkPointer();
		Object vec = vector.jsObj;
		com.dragome.commons.javascript.ScriptHelper.evalNoResult("value[0]=vec.x();value[1]=vec.y();value[2]=vec.z();",null);
    }

    public static void set(Vector3 in, btVector3 out) {
		out.checkPointer();
		btVector3.localArr_1[0] = in.x;
		btVector3.localArr_1[1] = in.y;
		btVector3.localArr_1[2] = in.z;
		btVector3.set(out, btVector3.localArr_1);
    }

    public static void get(btVector3 in, Vector3 out) {
		in.checkPointer();
		btVector3.get(in, btVector3.localArr_1);
		out.set(btVector3.localArr_1);
    }
}
