// Generated by esidl 0.4.0.

package org.w3c.dom.ranges;

public class RangeException extends RuntimeException
{
    public RangeException(short code, String message)
    {
        super(message);
        this.code = code;
    }
    public static final short BAD_BOUNDARYPOINTS_ERR = 1;
    public static final short INVALID_NODE_TYPE_ERR = 2;
    public short code;
}
