ignore-resources=org/teavm/backend/c
ignore-resources=CMakeLists.txt
ignore-resources=app_include.c
ignore-resources=android_jni.c
ignore-resources=external_cpp/teavm_optimizations/teavm/teavm_spritebatch.c
