
var Box2DLib = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Box2DLib) {
  Box2DLib = Box2DLib || {};


var a;a||(a=typeof Box2DLib !== 'undefined' ? Box2DLib : {});var f=Object.assign,h,k;a.ready=new Promise(function(b,c){h=b;k=c});var m=f({},a),n="object"===typeof window,p="function"===typeof importScripts,q="",r,t,u,fs,v,w;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)q=p?require("path").dirname(q)+"/":__dirname+"/",w=function(){v||(fs=require("fs"),v=require("path"))},r=function(b,c){w();b=v.normalize(b);return fs.readFileSync(b,c?null:"utf8")},u=function(b){b=r(b,!0);b.buffer||(b=new Uint8Array(b));return b},t=function(b,c,g){w();b=v.normalize(b);fs.readFile(b,function(e,d){e?g(e):c(d.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;}),a.inspect=function(){return"[Emscripten Module object]"};else if(n||p)p?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="",r=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},p&&(u=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),t=function(b,c,g){var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):g()};e.onerror=g;e.send(null)};a.print||console.log.bind(console);var x=a.printErr||console.warn.bind(console);f(a,m);m=null;var y;a.wasmBinary&&(y=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;
"object"!==typeof WebAssembly&&z("no native wasm support detected");var A,B=!1,C="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,D,E,F=[],G=[],H=[];function aa(){var b=a.preRun.shift();F.unshift(b)}var I=0,J=null,K=null;a.preloadedImages={};a.preloadedAudios={};function z(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";x(b);B=!0;b=new WebAssembly.RuntimeError(b+". Build with -s ASSERTIONS=1 for more info.");k(b);throw b;}
function L(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="box2D.wasm.wasm";if(!L()){var N=M;M=a.locateFile?a.locateFile(N,q):q+N}function O(){var b=M;try{if(b==M&&y)return new Uint8Array(y);if(u)return u(b);throw"both async and sync fetching of the wasm failed";}catch(c){z(c)}}
function ba(){if(!y&&(n||p)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+M+"'";return b.arrayBuffer()}).catch(function(){return O()});if(t)return new Promise(function(b,c){t(M,function(g){b(new Uint8Array(g))},c)})}return Promise.resolve().then(function(){return O()})}
function P(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var g=c.I;"number"===typeof g?void 0===c.C?Q(g)():Q(g)(c.C):g(void 0===c.C?null:c.C)}}}var R=[];function Q(b){var c=R[b];c||(b>=R.length&&(R.length=b+1),R[b]=c=E.get(b));return c}var ca={b:function(){z("")},a:function(){z("OOM")}};
(function(){function b(d){a.asm=d.exports;A=a.asm.c;d=A.buffer;a.HEAP8=new Int8Array(d);a.HEAP16=new Int16Array(d);a.HEAP32=new Int32Array(d);a.HEAPU8=D=new Uint8Array(d);a.HEAPU16=new Uint16Array(d);a.HEAPU32=new Uint32Array(d);a.HEAPF32=new Float32Array(d);a.HEAPF64=new Float64Array(d);E=a.asm.s;G.unshift(a.asm.d);I--;a.monitorRunDependencies&&a.monitorRunDependencies(I);0==I&&(null!==J&&(clearInterval(J),J=null),K&&(d=K,K=null,d()))}function c(d){b(d.instance)}function g(d){return ba().then(function(l){return WebAssembly.instantiate(l,
e)}).then(function(l){return l}).then(d,function(l){x("failed to asynchronously prepare wasm: "+l);z(l)})}var e={a:ca};I++;a.monitorRunDependencies&&a.monitorRunDependencies(I);if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(d){return x("Module.instantiateWasm callback failed with error: "+d),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||L()||M.startsWith("file://")||"function"!==typeof fetch?g(c):fetch(M,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,
e).then(c,function(l){x("wasm streaming compile failed: "+l);x("falling back to ArrayBuffer instantiation");return g(c)})})})().catch(k);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.d).apply(null,arguments)};
var S=a._emscripten_bind_VoidPtr___destroy___0=function(){return(S=a._emscripten_bind_VoidPtr___destroy___0=a.asm.e).apply(null,arguments)},da=a._emscripten_bind_b2Vec2_b2Vec2_0=function(){return(da=a._emscripten_bind_b2Vec2_b2Vec2_0=a.asm.f).apply(null,arguments)},ea=a._emscripten_bind_b2Vec2_b2Vec2_2=function(){return(ea=a._emscripten_bind_b2Vec2_b2Vec2_2=a.asm.g).apply(null,arguments)},fa=a._emscripten_bind_b2Vec2_SetZero_0=function(){return(fa=a._emscripten_bind_b2Vec2_SetZero_0=a.asm.h).apply(null,
arguments)},ha=a._emscripten_bind_b2Vec2_Set_2=function(){return(ha=a._emscripten_bind_b2Vec2_Set_2=a.asm.i).apply(null,arguments)},ia=a._emscripten_bind_b2Vec2_Length_0=function(){return(ia=a._emscripten_bind_b2Vec2_Length_0=a.asm.j).apply(null,arguments)},ja=a._emscripten_bind_b2Vec2_LengthSquared_0=function(){return(ja=a._emscripten_bind_b2Vec2_LengthSquared_0=a.asm.k).apply(null,arguments)},ka=a._emscripten_bind_b2Vec2_Normalize_0=function(){return(ka=a._emscripten_bind_b2Vec2_Normalize_0=a.asm.l).apply(null,
arguments)},la=a._emscripten_bind_b2Vec2_IsValid_0=function(){return(la=a._emscripten_bind_b2Vec2_IsValid_0=a.asm.m).apply(null,arguments)},ma=a._emscripten_bind_b2Vec2_get_x_0=function(){return(ma=a._emscripten_bind_b2Vec2_get_x_0=a.asm.n).apply(null,arguments)},na=a._emscripten_bind_b2Vec2_set_x_1=function(){return(na=a._emscripten_bind_b2Vec2_set_x_1=a.asm.o).apply(null,arguments)},pa=a._emscripten_bind_b2Vec2_get_y_0=function(){return(pa=a._emscripten_bind_b2Vec2_get_y_0=a.asm.p).apply(null,arguments)},
qa=a._emscripten_bind_b2Vec2_set_y_1=function(){return(qa=a._emscripten_bind_b2Vec2_set_y_1=a.asm.q).apply(null,arguments)},ra=a._emscripten_bind_b2Vec2___destroy___0=function(){return(ra=a._emscripten_bind_b2Vec2___destroy___0=a.asm.r).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.t).apply(null,arguments)};a._free=function(){return(a._free=a.asm.u).apply(null,arguments)};
a.UTF8ToString=function(b,c){if(b){var g=D,e=b+c;for(c=b;g[c]&&!(c>=e);)++c;if(16<c-b&&g.subarray&&C)b=C.decode(g.subarray(b,c));else{for(e="";b<c;){var d=g[b++];if(d&128){var l=g[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|l);else{var oa=g[b++]&63;d=224==(d&240)?(d&15)<<12|l<<6|oa:(d&7)<<18|l<<12|oa<<6|g[b++]&63;65536>d?e+=String.fromCharCode(d):(d-=65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}b=e}}else b="";return b};var T;
K=function sa(){T||U();T||(K=sa)};
function U(){function b(){if(!T&&(T=!0,a.calledRun=!0,!B)){P(G);h(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();H.unshift(c)}P(H)}}if(!(0<I)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)aa();P(F);0<I||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=U;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();U();function V(){}V.prototype=Object.create(V.prototype);V.prototype.constructor=V;V.prototype.A=V;V.B={};a.WrapperObject=V;function W(b){return(b||V).B}a.getCache=W;function X(b,c){var g=W(c),e=g[b];if(e)return e;e=Object.create((c||V).prototype);e.v=b;return g[b]=e}a.wrapPointer=X;a.castObject=function(b,c){return X(b.v,c)};a.NULL=X(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete W(b.A)[b.v]};a.compare=function(b,c){return b.v===c.v};a.getPointer=function(b){return b.v};a.getClass=function(b){return b.A};function Y(){throw"cannot construct a VoidPtr, no constructor in IDL";}Y.prototype=Object.create(V.prototype);Y.prototype.constructor=Y;Y.prototype.A=Y;Y.B={};a.VoidPtr=Y;Y.prototype.__destroy__=function(){S(this.v)};
function Z(b,c){b&&"object"===typeof b&&(b=b.v);c&&"object"===typeof c&&(c=c.v);this.v=void 0===b?da():void 0===c?_emscripten_bind_b2Vec2_b2Vec2_1(b):ea(b,c);W(Z)[this.v]=this}Z.prototype=Object.create(V.prototype);Z.prototype.constructor=Z;Z.prototype.A=Z;Z.B={};a.b2Vec2=Z;Z.prototype.SetZero=function(){fa(this.v)};Z.prototype.Set=Z.prototype.Set=function(b,c){var g=this.v;b&&"object"===typeof b&&(b=b.v);c&&"object"===typeof c&&(c=c.v);ha(g,b,c)};Z.prototype.Length=function(){return ia(this.v)};
Z.prototype.LengthSquared=function(){return ja(this.v)};Z.prototype.Normalize=function(){return ka(this.v)};Z.prototype.IsValid=function(){return!!la(this.v)};Z.prototype.get_x=Z.prototype.D=function(){return ma(this.v)};Z.prototype.set_x=Z.prototype.G=function(b){var c=this.v;b&&"object"===typeof b&&(b=b.v);na(c,b)};Object.defineProperty(Z.prototype,"x",{get:Z.prototype.D,set:Z.prototype.G});Z.prototype.get_y=Z.prototype.F=function(){return pa(this.v)};
Z.prototype.set_y=Z.prototype.H=function(b){var c=this.v;b&&"object"===typeof b&&(b=b.v);qa(c,b)};Object.defineProperty(Z.prototype,"y",{get:Z.prototype.F,set:Z.prototype.H});Z.prototype.__destroy__=function(){ra(this.v)};


  return Box2DLib.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Box2DLib;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Box2DLib; });
else if (typeof exports === 'object')
  exports["Box2DLib"] = Box2DLib;
