
var Box2DLib = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Box2DLib) {
  Box2DLib = Box2DLib || {};


var a;a||(a=typeof Box2DLib !== 'undefined' ? Box2DLib : {});var d=Object.assign,g,k;a.ready=new Promise(function(b,c){g=b;k=c});var l=d({},a),m="object"===typeof window,n="function"===typeof importScripts,q="",r,t,u,fs,v,w;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)q=n?require("path").dirname(q)+"/":__dirname+"/",w=function(){v||(fs=require("fs"),v=require("path"))},r=function(b,c){w();b=v.normalize(b);return fs.readFileSync(b,c?null:"utf8")},u=function(b){b=r(b,!0);b.buffer||(b=new Uint8Array(b));return b},t=function(b,c,f){w();b=v.normalize(b);fs.readFile(b,function(h,e){h?f(h):c(e.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;}),a.inspect=function(){return"[Emscripten Module object]"};else if(m||n)n?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="",r=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},n&&(u=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),t=function(b,c,f){var h=new XMLHttpRequest;h.open("GET",b,!0);h.responseType="arraybuffer";h.onload=function(){200==h.status||0==h.status&&h.response?c(h.response):f()};h.onerror=f;h.send(null)};a.print||console.log.bind(console);var x=a.printErr||console.warn.bind(console);d(a,l);l=null;var y;a.wasmBinary&&(y=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;
"object"!==typeof WebAssembly&&z("no native wasm support detected");var A,B=!1,C="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,D,E,F=[],G=[],H=[],I=!1;function aa(){var b=a.preRun.shift();F.unshift(b)}var J=0,K=null,L=null;a.preloadedImages={};a.preloadedAudios={};function z(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";x(b);B=!0;b=new WebAssembly.RuntimeError(b+". Build with -s ASSERTIONS=1 for more info.");k(b);throw b;}
function M(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="box2D.wasm.wasm";if(!M()){var ba=N;N=a.locateFile?a.locateFile(ba,q):q+ba}function ca(){var b=N;try{if(b==N&&y)return new Uint8Array(y);if(u)return u(b);throw"both async and sync fetching of the wasm failed";}catch(c){z(c)}}
function da(){if(!y&&(m||n)){if("function"===typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+N+"'";return b.arrayBuffer()}).catch(function(){return ca()});if(t)return new Promise(function(b,c){t(N,function(f){b(new Uint8Array(f))},c)})}return Promise.resolve().then(function(){return ca()})}
function O(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var f=c.Qa;"number"===typeof f?void 0===c.la?ea(f)():ea(f)(c.la):f(void 0===c.la?null:c.la)}}}var P=[];function ea(b){var c=P[b];c||(b>=P.length&&(P.length=b+1),P[b]=c=E.get(b));return c}var fa={c:function(){z("")},a:function(b,c,f){D.copyWithin(b,c,c+f)},b:function(){z("OOM")}};
(function(){function b(e){a.asm=e.exports;A=a.asm.d;e=A.buffer;a.HEAP8=new Int8Array(e);a.HEAP16=new Int16Array(e);a.HEAP32=new Int32Array(e);a.HEAPU8=D=new Uint8Array(e);a.HEAPU16=new Uint16Array(e);a.HEAPU32=new Uint32Array(e);a.HEAPF32=new Float32Array(e);a.HEAPF64=new Float64Array(e);E=a.asm.fa;G.unshift(a.asm.e);J--;a.monitorRunDependencies&&a.monitorRunDependencies(J);0==J&&(null!==K&&(clearInterval(K),K=null),L&&(e=L,L=null,e()))}function c(e){b(e.instance)}function f(e){return da().then(function(p){return WebAssembly.instantiate(p,
h)}).then(function(p){return p}).then(e,function(p){x("failed to asynchronously prepare wasm: "+p);z(p)})}var h={a:fa};J++;a.monitorRunDependencies&&a.monitorRunDependencies(J);if(a.instantiateWasm)try{return a.instantiateWasm(h,b)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||M()||N.startsWith("file://")||"function"!==typeof fetch?f(c):fetch(N,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
h).then(c,function(p){x("wasm streaming compile failed: "+p);x("falling back to ArrayBuffer instantiation");return f(c)})})})().catch(k);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};
var ha=a._emscripten_bind_VoidPtr___destroy___0=function(){return(ha=a._emscripten_bind_VoidPtr___destroy___0=a.asm.f).apply(null,arguments)},ia=a._emscripten_bind_b2World_b2World_1=function(){return(ia=a._emscripten_bind_b2World_b2World_1=a.asm.g).apply(null,arguments)},ja=a._emscripten_bind_b2World_Step_3=function(){return(ja=a._emscripten_bind_b2World_Step_3=a.asm.h).apply(null,arguments)},ka=a._emscripten_bind_b2World_GetGravity_0=function(){return(ka=a._emscripten_bind_b2World_GetGravity_0=a.asm.i).apply(null,
arguments)},la=a._emscripten_bind_b2World_CreateBody_1=function(){return(la=a._emscripten_bind_b2World_CreateBody_1=a.asm.j).apply(null,arguments)},ma=a._emscripten_bind_b2World_DestroyBody_1=function(){return(ma=a._emscripten_bind_b2World_DestroyBody_1=a.asm.k).apply(null,arguments)},na=a._emscripten_bind_b2World___destroy___0=function(){return(na=a._emscripten_bind_b2World___destroy___0=a.asm.l).apply(null,arguments)},oa=a._emscripten_bind_b2Vec2_b2Vec2_0=function(){return(oa=a._emscripten_bind_b2Vec2_b2Vec2_0=
a.asm.m).apply(null,arguments)},pa=a._emscripten_bind_b2Vec2_b2Vec2_2=function(){return(pa=a._emscripten_bind_b2Vec2_b2Vec2_2=a.asm.n).apply(null,arguments)},qa=a._emscripten_bind_b2Vec2_SetZero_0=function(){return(qa=a._emscripten_bind_b2Vec2_SetZero_0=a.asm.o).apply(null,arguments)},ra=a._emscripten_bind_b2Vec2_Set_2=function(){return(ra=a._emscripten_bind_b2Vec2_Set_2=a.asm.p).apply(null,arguments)},sa=a._emscripten_bind_b2Vec2_Length_0=function(){return(sa=a._emscripten_bind_b2Vec2_Length_0=a.asm.q).apply(null,
arguments)},ta=a._emscripten_bind_b2Vec2_LengthSquared_0=function(){return(ta=a._emscripten_bind_b2Vec2_LengthSquared_0=a.asm.r).apply(null,arguments)},ua=a._emscripten_bind_b2Vec2_Normalize_0=function(){return(ua=a._emscripten_bind_b2Vec2_Normalize_0=a.asm.s).apply(null,arguments)},va=a._emscripten_bind_b2Vec2_IsValid_0=function(){return(va=a._emscripten_bind_b2Vec2_IsValid_0=a.asm.t).apply(null,arguments)},wa=a._emscripten_bind_b2Vec2_get_x_0=function(){return(wa=a._emscripten_bind_b2Vec2_get_x_0=
a.asm.u).apply(null,arguments)},xa=a._emscripten_bind_b2Vec2_set_x_1=function(){return(xa=a._emscripten_bind_b2Vec2_set_x_1=a.asm.v).apply(null,arguments)},ya=a._emscripten_bind_b2Vec2_get_y_0=function(){return(ya=a._emscripten_bind_b2Vec2_get_y_0=a.asm.w).apply(null,arguments)},za=a._emscripten_bind_b2Vec2_set_y_1=function(){return(za=a._emscripten_bind_b2Vec2_set_y_1=a.asm.x).apply(null,arguments)},Aa=a._emscripten_bind_b2Vec2___destroy___0=function(){return(Aa=a._emscripten_bind_b2Vec2___destroy___0=
a.asm.y).apply(null,arguments)},Ba=a._emscripten_bind_b2BodyDef_b2BodyDef_0=function(){return(Ba=a._emscripten_bind_b2BodyDef_b2BodyDef_0=a.asm.z).apply(null,arguments)},Ca=a._emscripten_bind_b2BodyDef_get_type_0=function(){return(Ca=a._emscripten_bind_b2BodyDef_get_type_0=a.asm.A).apply(null,arguments)},Da=a._emscripten_bind_b2BodyDef_set_type_1=function(){return(Da=a._emscripten_bind_b2BodyDef_set_type_1=a.asm.B).apply(null,arguments)},Ea=a._emscripten_bind_b2BodyDef_get_position_0=function(){return(Ea=
a._emscripten_bind_b2BodyDef_get_position_0=a.asm.C).apply(null,arguments)},Fa=a._emscripten_bind_b2BodyDef_set_position_1=function(){return(Fa=a._emscripten_bind_b2BodyDef_set_position_1=a.asm.D).apply(null,arguments)},Ga=a._emscripten_bind_b2BodyDef_get_angle_0=function(){return(Ga=a._emscripten_bind_b2BodyDef_get_angle_0=a.asm.E).apply(null,arguments)},Ha=a._emscripten_bind_b2BodyDef_set_angle_1=function(){return(Ha=a._emscripten_bind_b2BodyDef_set_angle_1=a.asm.F).apply(null,arguments)},Ia=a._emscripten_bind_b2BodyDef_get_linearVelocity_0=
function(){return(Ia=a._emscripten_bind_b2BodyDef_get_linearVelocity_0=a.asm.G).apply(null,arguments)},Ja=a._emscripten_bind_b2BodyDef_set_linearVelocity_1=function(){return(Ja=a._emscripten_bind_b2BodyDef_set_linearVelocity_1=a.asm.H).apply(null,arguments)},Ka=a._emscripten_bind_b2BodyDef_get_angularVelocity_0=function(){return(Ka=a._emscripten_bind_b2BodyDef_get_angularVelocity_0=a.asm.I).apply(null,arguments)},La=a._emscripten_bind_b2BodyDef_set_angularVelocity_1=function(){return(La=a._emscripten_bind_b2BodyDef_set_angularVelocity_1=
a.asm.J).apply(null,arguments)},Ma=a._emscripten_bind_b2BodyDef_get_linearDamping_0=function(){return(Ma=a._emscripten_bind_b2BodyDef_get_linearDamping_0=a.asm.K).apply(null,arguments)},Na=a._emscripten_bind_b2BodyDef_set_linearDamping_1=function(){return(Na=a._emscripten_bind_b2BodyDef_set_linearDamping_1=a.asm.L).apply(null,arguments)},Oa=a._emscripten_bind_b2BodyDef_get_angularDamping_0=function(){return(Oa=a._emscripten_bind_b2BodyDef_get_angularDamping_0=a.asm.M).apply(null,arguments)},Pa=a._emscripten_bind_b2BodyDef_set_angularDamping_1=
function(){return(Pa=a._emscripten_bind_b2BodyDef_set_angularDamping_1=a.asm.N).apply(null,arguments)},Qa=a._emscripten_bind_b2BodyDef_get_allowSleep_0=function(){return(Qa=a._emscripten_bind_b2BodyDef_get_allowSleep_0=a.asm.O).apply(null,arguments)},Ra=a._emscripten_bind_b2BodyDef_set_allowSleep_1=function(){return(Ra=a._emscripten_bind_b2BodyDef_set_allowSleep_1=a.asm.P).apply(null,arguments)},Sa=a._emscripten_bind_b2BodyDef_get_awake_0=function(){return(Sa=a._emscripten_bind_b2BodyDef_get_awake_0=
a.asm.Q).apply(null,arguments)},Ta=a._emscripten_bind_b2BodyDef_set_awake_1=function(){return(Ta=a._emscripten_bind_b2BodyDef_set_awake_1=a.asm.R).apply(null,arguments)},Ua=a._emscripten_bind_b2BodyDef_get_fixedRotation_0=function(){return(Ua=a._emscripten_bind_b2BodyDef_get_fixedRotation_0=a.asm.S).apply(null,arguments)},Va=a._emscripten_bind_b2BodyDef_set_fixedRotation_1=function(){return(Va=a._emscripten_bind_b2BodyDef_set_fixedRotation_1=a.asm.T).apply(null,arguments)},Wa=a._emscripten_bind_b2BodyDef_get_bullet_0=
function(){return(Wa=a._emscripten_bind_b2BodyDef_get_bullet_0=a.asm.U).apply(null,arguments)},Xa=a._emscripten_bind_b2BodyDef_set_bullet_1=function(){return(Xa=a._emscripten_bind_b2BodyDef_set_bullet_1=a.asm.V).apply(null,arguments)},Ya=a._emscripten_bind_b2BodyDef_get_active_0=function(){return(Ya=a._emscripten_bind_b2BodyDef_get_active_0=a.asm.W).apply(null,arguments)},Za=a._emscripten_bind_b2BodyDef_set_active_1=function(){return(Za=a._emscripten_bind_b2BodyDef_set_active_1=a.asm.X).apply(null,
arguments)},$a=a._emscripten_bind_b2BodyDef_get_gravityScale_0=function(){return($a=a._emscripten_bind_b2BodyDef_get_gravityScale_0=a.asm.Y).apply(null,arguments)},ab=a._emscripten_bind_b2BodyDef_set_gravityScale_1=function(){return(ab=a._emscripten_bind_b2BodyDef_set_gravityScale_1=a.asm.Z).apply(null,arguments)},bb=a._emscripten_bind_b2BodyDef___destroy___0=function(){return(bb=a._emscripten_bind_b2BodyDef___destroy___0=a.asm._).apply(null,arguments)},cb=a._emscripten_bind_b2Body_GetAngle_0=function(){return(cb=
a._emscripten_bind_b2Body_GetAngle_0=a.asm.$).apply(null,arguments)},db=a._emscripten_bind_b2Body_SetType_1=function(){return(db=a._emscripten_bind_b2Body_SetType_1=a.asm.aa).apply(null,arguments)},eb=a._emscripten_bind_b2Body_GetType_0=function(){return(eb=a._emscripten_bind_b2Body_GetType_0=a.asm.ba).apply(null,arguments)},gb=a._emscripten_enum_b2BodyType_b2_staticBody=function(){return(gb=a._emscripten_enum_b2BodyType_b2_staticBody=a.asm.ca).apply(null,arguments)},hb=a._emscripten_enum_b2BodyType_b2_kinematicBody=
function(){return(hb=a._emscripten_enum_b2BodyType_b2_kinematicBody=a.asm.da).apply(null,arguments)},ib=a._emscripten_enum_b2BodyType_b2_dynamicBody=function(){return(ib=a._emscripten_enum_b2BodyType_b2_dynamicBody=a.asm.ea).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.ga).apply(null,arguments)};a._free=function(){return(a._free=a.asm.ha).apply(null,arguments)};
a.UTF8ToString=function(b,c){if(b){var f=D,h=b+c;for(c=b;f[c]&&!(c>=h);)++c;if(16<c-b&&f.subarray&&C)b=C.decode(f.subarray(b,c));else{for(h="";b<c;){var e=f[b++];if(e&128){var p=f[b++]&63;if(192==(e&224))h+=String.fromCharCode((e&31)<<6|p);else{var fb=f[b++]&63;e=224==(e&240)?(e&15)<<12|p<<6|fb:(e&7)<<18|p<<12|fb<<6|f[b++]&63;65536>e?h+=String.fromCharCode(e):(e-=65536,h+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else h+=String.fromCharCode(e)}b=h}}else b="";return b};var Q;
L=function jb(){Q||R();Q||(L=jb)};
function R(){function b(){if(!Q&&(Q=!0,a.calledRun=!0,!B)){I=!0;O(G);g(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();H.unshift(c)}O(H)}}if(!(0<J)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)aa();O(F);0<J||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=R;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();R();function S(){}S.prototype=Object.create(S.prototype);S.prototype.constructor=S;S.prototype.ja=S;S.ka={};a.WrapperObject=S;function T(b){return(b||S).ka}a.getCache=T;function U(b,c){var f=T(c),h=f[b];if(h)return h;h=Object.create((c||S).prototype);h.ia=b;return f[b]=h}a.wrapPointer=U;a.castObject=function(b,c){return U(b.ia,c)};a.NULL=U(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete T(b.ja)[b.ia]};a.compare=function(b,c){return b.ia===c.ia};a.getPointer=function(b){return b.ia};a.getClass=function(b){return b.ja};function V(){throw"cannot construct a VoidPtr, no constructor in IDL";}V.prototype=Object.create(S.prototype);V.prototype.constructor=V;V.prototype.ja=V;V.ka={};a.VoidPtr=V;V.prototype.__destroy__=function(){ha(this.ia)};
function W(b){b&&"object"===typeof b&&(b=b.ia);this.ia=ia(b);T(W)[this.ia]=this}W.prototype=Object.create(S.prototype);W.prototype.constructor=W;W.prototype.ja=W;W.ka={};a.b2World=W;W.prototype.Step=function(b,c,f){var h=this.ia;b&&"object"===typeof b&&(b=b.ia);c&&"object"===typeof c&&(c=c.ia);f&&"object"===typeof f&&(f=f.ia);ja(h,b,c,f)};W.prototype.GetGravity=function(){return U(ka(this.ia),X)};W.prototype.CreateBody=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);return U(la(c,b),Y)};
W.prototype.DestroyBody=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);ma(c,b)};W.prototype.__destroy__=function(){na(this.ia)};function X(b,c){b&&"object"===typeof b&&(b=b.ia);c&&"object"===typeof c&&(c=c.ia);this.ia=void 0===b?oa():void 0===c?_emscripten_bind_b2Vec2_b2Vec2_1(b):pa(b,c);T(X)[this.ia]=this}X.prototype=Object.create(S.prototype);X.prototype.constructor=X;X.prototype.ja=X;X.ka={};a.b2Vec2=X;X.prototype.SetZero=function(){qa(this.ia)};
X.prototype.Set=X.prototype.Set=function(b,c){var f=this.ia;b&&"object"===typeof b&&(b=b.ia);c&&"object"===typeof c&&(c=c.ia);ra(f,b,c)};X.prototype.Length=function(){return sa(this.ia)};X.prototype.LengthSquared=function(){return ta(this.ia)};X.prototype.Normalize=function(){return ua(this.ia)};X.prototype.IsValid=function(){return!!va(this.ia)};X.prototype.get_x=X.prototype.za=function(){return wa(this.ia)};
X.prototype.set_x=X.prototype.Oa=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);xa(c,b)};Object.defineProperty(X.prototype,"x",{get:X.prototype.za,set:X.prototype.Oa});X.prototype.get_y=X.prototype.Aa=function(){return ya(this.ia)};X.prototype.set_y=X.prototype.Pa=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);za(c,b)};Object.defineProperty(X.prototype,"y",{get:X.prototype.Aa,set:X.prototype.Pa});X.prototype.__destroy__=function(){Aa(this.ia)};
function Z(){this.ia=Ba();T(Z)[this.ia]=this}Z.prototype=Object.create(S.prototype);Z.prototype.constructor=Z;Z.prototype.ja=Z;Z.ka={};a.b2BodyDef=Z;Z.prototype.get_type=Z.prototype.ya=function(){return Ca(this.ia)};Z.prototype.set_type=Z.prototype.Na=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Da(c,b)};Object.defineProperty(Z.prototype,"type",{get:Z.prototype.ya,set:Z.prototype.Na});Z.prototype.get_position=Z.prototype.xa=function(){return U(Ea(this.ia),X)};
Z.prototype.set_position=Z.prototype.Ma=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Fa(c,b)};Object.defineProperty(Z.prototype,"position",{get:Z.prototype.xa,set:Z.prototype.Ma});Z.prototype.get_angle=Z.prototype.oa=function(){return Ga(this.ia)};Z.prototype.set_angle=Z.prototype.Da=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Ha(c,b)};Object.defineProperty(Z.prototype,"angle",{get:Z.prototype.oa,set:Z.prototype.Da});
Z.prototype.get_linearVelocity=Z.prototype.wa=function(){return U(Ia(this.ia),X)};Z.prototype.set_linearVelocity=Z.prototype.La=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Ja(c,b)};Object.defineProperty(Z.prototype,"linearVelocity",{get:Z.prototype.wa,set:Z.prototype.La});Z.prototype.get_angularVelocity=Z.prototype.qa=function(){return Ka(this.ia)};Z.prototype.set_angularVelocity=Z.prototype.Fa=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);La(c,b)};
Object.defineProperty(Z.prototype,"angularVelocity",{get:Z.prototype.qa,set:Z.prototype.Fa});Z.prototype.get_linearDamping=Z.prototype.va=function(){return Ma(this.ia)};Z.prototype.set_linearDamping=Z.prototype.Ka=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Na(c,b)};Object.defineProperty(Z.prototype,"linearDamping",{get:Z.prototype.va,set:Z.prototype.Ka});Z.prototype.get_angularDamping=Z.prototype.pa=function(){return Oa(this.ia)};
Z.prototype.set_angularDamping=Z.prototype.Ea=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Pa(c,b)};Object.defineProperty(Z.prototype,"angularDamping",{get:Z.prototype.pa,set:Z.prototype.Ea});Z.prototype.get_allowSleep=Z.prototype.na=function(){return!!Qa(this.ia)};Z.prototype.set_allowSleep=Z.prototype.Ca=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Ra(c,b)};Object.defineProperty(Z.prototype,"allowSleep",{get:Z.prototype.na,set:Z.prototype.Ca});
Z.prototype.get_awake=Z.prototype.ra=function(){return!!Sa(this.ia)};Z.prototype.set_awake=Z.prototype.Ga=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Ta(c,b)};Object.defineProperty(Z.prototype,"awake",{get:Z.prototype.ra,set:Z.prototype.Ga});Z.prototype.get_fixedRotation=Z.prototype.ta=function(){return!!Ua(this.ia)};Z.prototype.set_fixedRotation=Z.prototype.Ia=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Va(c,b)};
Object.defineProperty(Z.prototype,"fixedRotation",{get:Z.prototype.ta,set:Z.prototype.Ia});Z.prototype.get_bullet=Z.prototype.sa=function(){return!!Wa(this.ia)};Z.prototype.set_bullet=Z.prototype.Ha=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Xa(c,b)};Object.defineProperty(Z.prototype,"bullet",{get:Z.prototype.sa,set:Z.prototype.Ha});Z.prototype.get_active=Z.prototype.ma=function(){return!!Ya(this.ia)};
Z.prototype.set_active=Z.prototype.Ba=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);Za(c,b)};Object.defineProperty(Z.prototype,"active",{get:Z.prototype.ma,set:Z.prototype.Ba});Z.prototype.get_gravityScale=Z.prototype.ua=function(){return $a(this.ia)};Z.prototype.set_gravityScale=Z.prototype.Ja=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);ab(c,b)};Object.defineProperty(Z.prototype,"gravityScale",{get:Z.prototype.ua,set:Z.prototype.Ja});Z.prototype.__destroy__=function(){bb(this.ia)};
function Y(){throw"cannot construct a b2Body, no constructor in IDL";}Y.prototype=Object.create(S.prototype);Y.prototype.constructor=Y;Y.prototype.ja=Y;Y.ka={};a.b2Body=Y;Y.prototype.GetAngle=function(){return cb(this.ia)};Y.prototype.SetType=function(b){var c=this.ia;b&&"object"===typeof b&&(b=b.ia);db(c,b)};Y.prototype.GetType=function(){return eb(this.ia)};(function(){function b(){a.b2_staticBody=gb();a.b2_kinematicBody=hb();a.b2_dynamicBody=ib()}I?b():G.unshift(b)})();


  return Box2DLib.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Box2DLib;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Box2DLib; });
else if (typeof exports === 'object')
  exports["Box2DLib"] = Box2DLib;
