
var Box2DLib = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Box2DLib) {
  Box2DLib = Box2DLib || {};


var a;a||(a=typeof Box2DLib !== 'undefined' ? Box2DLib : {});var g=Object.assign,h,k;a.ready=new Promise(function(b,c){h=b;k=c});var l=g({},a),n="object"===typeof window,p="function"===typeof importScripts,q="",r,t,u,fs,v,w;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)q=p?require("path").dirname(q)+"/":__dirname+"/",w=function(){v||(fs=require("fs"),v=require("path"))},r=function(b,c){w();b=v.normalize(b);return fs.readFileSync(b,c?null:"utf8")},u=function(b){b=r(b,!0);b.buffer||(b=new Uint8Array(b));return b},t=function(b,c,e){w();b=v.normalize(b);fs.readFile(b,function(f,d){f?e(f):c(d.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;}),a.inspect=function(){return"[Emscripten Module object]"};else if(n||p)p?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="",r=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},p&&(u=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),t=function(b,c,e){var f=new XMLHttpRequest;f.open("GET",b,!0);f.responseType="arraybuffer";f.onload=function(){200==f.status||0==f.status&&f.response?c(f.response):e()};f.onerror=e;f.send(null)};a.print||console.log.bind(console);var x=a.printErr||console.warn.bind(console);g(a,l);l=null;var y;a.wasmBinary&&(y=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;
"object"!==typeof WebAssembly&&z("no native wasm support detected");var A,B=!1,C="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,D,E,F=[],G=[],H=[];function aa(){var b=a.preRun.shift();F.unshift(b)}var I=0,J=null,K=null;a.preloadedImages={};a.preloadedAudios={};function z(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";x(b);B=!0;b=new WebAssembly.RuntimeError(b+". Build with -s ASSERTIONS=1 for more info.");k(b);throw b;}
function L(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="box2D.wasm.wasm";if(!L()){var N=M;M=a.locateFile?a.locateFile(N,q):q+N}function O(){var b=M;try{if(b==M&&y)return new Uint8Array(y);if(u)return u(b);throw"both async and sync fetching of the wasm failed";}catch(c){z(c)}}
function ba(){if(!y&&(n||p)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+M+"'";return b.arrayBuffer()}).catch(function(){return O()});if(t)return new Promise(function(b,c){t(M,function(e){b(new Uint8Array(e))},c)})}return Promise.resolve().then(function(){return O()})}
function P(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var e=c.J;"number"===typeof e?void 0===c.D?Q(e)():Q(e)(c.D):e(void 0===c.D?null:c.D)}}}var R=[];function Q(b){var c=R[b];c||(b>=R.length&&(R.length=b+1),R[b]=c=E.get(b));return c}var ca={c:function(){z("")},a:function(b,c,e){D.copyWithin(b,c,c+e)},b:function(){z("OOM")}};
(function(){function b(d){a.asm=d.exports;A=a.asm.d;d=A.buffer;a.HEAP8=new Int8Array(d);a.HEAP16=new Int16Array(d);a.HEAP32=new Int32Array(d);a.HEAPU8=D=new Uint8Array(d);a.HEAPU16=new Uint16Array(d);a.HEAPU32=new Uint32Array(d);a.HEAPF32=new Float32Array(d);a.HEAPF64=new Float64Array(d);E=a.asm.x;G.unshift(a.asm.e);I--;a.monitorRunDependencies&&a.monitorRunDependencies(I);0==I&&(null!==J&&(clearInterval(J),J=null),K&&(d=K,K=null,d()))}function c(d){b(d.instance)}function e(d){return ba().then(function(m){return WebAssembly.instantiate(m,
f)}).then(function(m){return m}).then(d,function(m){x("failed to asynchronously prepare wasm: "+m);z(m)})}var f={a:ca};I++;a.monitorRunDependencies&&a.monitorRunDependencies(I);if(a.instantiateWasm)try{return a.instantiateWasm(f,b)}catch(d){return x("Module.instantiateWasm callback failed with error: "+d),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||L()||M.startsWith("file://")||"function"!==typeof fetch?e(c):fetch(M,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,
f).then(c,function(m){x("wasm streaming compile failed: "+m);x("falling back to ArrayBuffer instantiation");return e(c)})})})().catch(k);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};
var da=a._emscripten_bind_VoidPtr___destroy___0=function(){return(da=a._emscripten_bind_VoidPtr___destroy___0=a.asm.f).apply(null,arguments)},ea=a._emscripten_bind_b2World_b2World_1=function(){return(ea=a._emscripten_bind_b2World_b2World_1=a.asm.g).apply(null,arguments)},fa=a._emscripten_bind_b2World_Step_3=function(){return(fa=a._emscripten_bind_b2World_Step_3=a.asm.h).apply(null,arguments)},ha=a._emscripten_bind_b2World_GetGravity_0=function(){return(ha=a._emscripten_bind_b2World_GetGravity_0=a.asm.i).apply(null,
arguments)},ia=a._emscripten_bind_b2World___destroy___0=function(){return(ia=a._emscripten_bind_b2World___destroy___0=a.asm.j).apply(null,arguments)},ja=a._emscripten_bind_b2Vec2_b2Vec2_0=function(){return(ja=a._emscripten_bind_b2Vec2_b2Vec2_0=a.asm.k).apply(null,arguments)},ka=a._emscripten_bind_b2Vec2_b2Vec2_2=function(){return(ka=a._emscripten_bind_b2Vec2_b2Vec2_2=a.asm.l).apply(null,arguments)},la=a._emscripten_bind_b2Vec2_SetZero_0=function(){return(la=a._emscripten_bind_b2Vec2_SetZero_0=a.asm.m).apply(null,
arguments)},ma=a._emscripten_bind_b2Vec2_Set_2=function(){return(ma=a._emscripten_bind_b2Vec2_Set_2=a.asm.n).apply(null,arguments)},na=a._emscripten_bind_b2Vec2_Length_0=function(){return(na=a._emscripten_bind_b2Vec2_Length_0=a.asm.o).apply(null,arguments)},oa=a._emscripten_bind_b2Vec2_LengthSquared_0=function(){return(oa=a._emscripten_bind_b2Vec2_LengthSquared_0=a.asm.p).apply(null,arguments)},pa=a._emscripten_bind_b2Vec2_Normalize_0=function(){return(pa=a._emscripten_bind_b2Vec2_Normalize_0=a.asm.q).apply(null,
arguments)},qa=a._emscripten_bind_b2Vec2_IsValid_0=function(){return(qa=a._emscripten_bind_b2Vec2_IsValid_0=a.asm.r).apply(null,arguments)},ra=a._emscripten_bind_b2Vec2_get_x_0=function(){return(ra=a._emscripten_bind_b2Vec2_get_x_0=a.asm.s).apply(null,arguments)},sa=a._emscripten_bind_b2Vec2_set_x_1=function(){return(sa=a._emscripten_bind_b2Vec2_set_x_1=a.asm.t).apply(null,arguments)},ua=a._emscripten_bind_b2Vec2_get_y_0=function(){return(ua=a._emscripten_bind_b2Vec2_get_y_0=a.asm.u).apply(null,arguments)},
va=a._emscripten_bind_b2Vec2_set_y_1=function(){return(va=a._emscripten_bind_b2Vec2_set_y_1=a.asm.v).apply(null,arguments)},wa=a._emscripten_bind_b2Vec2___destroy___0=function(){return(wa=a._emscripten_bind_b2Vec2___destroy___0=a.asm.w).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.y).apply(null,arguments)};a._free=function(){return(a._free=a.asm.z).apply(null,arguments)};
a.UTF8ToString=function(b,c){if(b){var e=D,f=b+c;for(c=b;e[c]&&!(c>=f);)++c;if(16<c-b&&e.subarray&&C)b=C.decode(e.subarray(b,c));else{for(f="";b<c;){var d=e[b++];if(d&128){var m=e[b++]&63;if(192==(d&224))f+=String.fromCharCode((d&31)<<6|m);else{var ta=e[b++]&63;d=224==(d&240)?(d&15)<<12|m<<6|ta:(d&7)<<18|m<<12|ta<<6|e[b++]&63;65536>d?f+=String.fromCharCode(d):(d-=65536,f+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else f+=String.fromCharCode(d)}b=f}}else b="";return b};var S;
K=function xa(){S||T();S||(K=xa)};
function T(){function b(){if(!S&&(S=!0,a.calledRun=!0,!B)){P(G);h(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();H.unshift(c)}P(H)}}if(!(0<I)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)aa();P(F);0<I||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=T;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();T();function U(){}U.prototype=Object.create(U.prototype);U.prototype.constructor=U;U.prototype.B=U;U.C={};a.WrapperObject=U;function V(b){return(b||U).C}a.getCache=V;function W(b,c){var e=V(c),f=e[b];if(f)return f;f=Object.create((c||U).prototype);f.A=b;return e[b]=f}a.wrapPointer=W;a.castObject=function(b,c){return W(b.A,c)};a.NULL=W(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete V(b.B)[b.A]};a.compare=function(b,c){return b.A===c.A};a.getPointer=function(b){return b.A};a.getClass=function(b){return b.B};function X(){throw"cannot construct a VoidPtr, no constructor in IDL";}X.prototype=Object.create(U.prototype);X.prototype.constructor=X;X.prototype.B=X;X.C={};a.VoidPtr=X;X.prototype.__destroy__=function(){da(this.A)};
function Y(b){b&&"object"===typeof b&&(b=b.A);this.A=ea(b);V(Y)[this.A]=this}Y.prototype=Object.create(U.prototype);Y.prototype.constructor=Y;Y.prototype.B=Y;Y.C={};a.b2World=Y;Y.prototype.Step=function(b,c,e){var f=this.A;b&&"object"===typeof b&&(b=b.A);c&&"object"===typeof c&&(c=c.A);e&&"object"===typeof e&&(e=e.A);fa(f,b,c,e)};Y.prototype.GetGravity=function(){return W(ha(this.A),Z)};Y.prototype.__destroy__=function(){ia(this.A)};
function Z(b,c){b&&"object"===typeof b&&(b=b.A);c&&"object"===typeof c&&(c=c.A);this.A=void 0===b?ja():void 0===c?_emscripten_bind_b2Vec2_b2Vec2_1(b):ka(b,c);V(Z)[this.A]=this}Z.prototype=Object.create(U.prototype);Z.prototype.constructor=Z;Z.prototype.B=Z;Z.C={};a.b2Vec2=Z;Z.prototype.SetZero=function(){la(this.A)};Z.prototype.Set=Z.prototype.Set=function(b,c){var e=this.A;b&&"object"===typeof b&&(b=b.A);c&&"object"===typeof c&&(c=c.A);ma(e,b,c)};Z.prototype.Length=function(){return na(this.A)};
Z.prototype.LengthSquared=function(){return oa(this.A)};Z.prototype.Normalize=function(){return pa(this.A)};Z.prototype.IsValid=function(){return!!qa(this.A)};Z.prototype.get_x=Z.prototype.F=function(){return ra(this.A)};Z.prototype.set_x=Z.prototype.H=function(b){var c=this.A;b&&"object"===typeof b&&(b=b.A);sa(c,b)};Object.defineProperty(Z.prototype,"x",{get:Z.prototype.F,set:Z.prototype.H});Z.prototype.get_y=Z.prototype.G=function(){return ua(this.A)};
Z.prototype.set_y=Z.prototype.I=function(b){var c=this.A;b&&"object"===typeof b&&(b=b.A);va(c,b)};Object.defineProperty(Z.prototype,"y",{get:Z.prototype.G,set:Z.prototype.I});Z.prototype.__destroy__=function(){wa(this.A)};


  return Box2DLib.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Box2DLib;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Box2DLib; });
else if (typeof exports === 'object')
  exports["Box2DLib"] = Box2DLib;
