// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface AudioTrack
{
    // AudioTrack
    public String getId();
    public String getKind();
    public String getLabel();
    public String getLanguage();
    public boolean getEnabled();
    public void setEnabled(boolean enabled);
}
