// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.events.Event;

public interface BeforeUnloadEvent extends Event
{
    // BeforeUnloadEvent
    public String getReturnValue();
    public void setReturnValue(String returnValue);
}
