// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.file.File;

public interface DataTransferItemList
{
    // DataTransferItemList
    public int getLength();
    public DataTransferItem getElement(int index);
    public void deleteElement(int index);
    public void clear();
    public DataTransferItem add(String data, String type);
    public DataTransferItem add(File data);
}
