// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.file.File;

public interface DataTransferItem
{
    // DataTransferItem
    public String getKind();
    public String getType();
    public void getAsString(FunctionStringCallback callback);
    public File getAsFile();
}
