// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLFrameSetElement extends HTMLElement
{
    // HTMLFrameSetElement
    public String getCols();
    public void setCols(String cols);
    public String getRows();
    public void setRows(String rows);
    public Function getOnafterprint();
    public void setOnafterprint(Function onafterprint);
    public Function getOnbeforeprint();
    public void setOnbeforeprint(Function onbeforeprint);
    public Function getOnbeforeunload();
    public void setOnbeforeunload(Function onbeforeunload);
    public Function getOnblur();
    public void setOnblur(Function onblur);
    public Function getOnerror();
    public void setOnerror(Function onerror);
    public Function getOnfocus();
    public void setOnfocus(Function onfocus);
    public Function getOnhashchange();
    public void setOnhashchange(Function onhashchange);
    public Function getOnload();
    public void setOnload(Function onload);
    public Function getOnmessage();
    public void setOnmessage(Function onmessage);
    public Function getOnoffline();
    public void setOnoffline(Function onoffline);
    public Function getOnonline();
    public void setOnonline(Function ononline);
    public Function getOnpagehide();
    public void setOnpagehide(Function onpagehide);
    public Function getOnpageshow();
    public void setOnpageshow(Function onpageshow);
    public Function getOnpopstate();
    public void setOnpopstate(Function onpopstate);
    public Function getOnredo();
    public void setOnredo(Function onredo);
    public Function getOnresize();
    public void setOnresize(Function onresize);
    public Function getOnscroll();
    public void setOnscroll(Function onscroll);
    public Function getOnstorage();
    public void setOnstorage(Function onstorage);
    public Function getOnundo();
    public void setOnundo(Function onundo);
    public Function getOnunload();
    public void setOnunload(Function onunload);
}
