// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLOptionsCollection extends HTMLCollection
{
    // HTMLOptionsCollection
    public int getLength();
    public void setLength(int length);
    public Object namedItem(String name);
    public void add(HTMLElement element);
    public void add(HTMLElement element, HTMLElement before);
    public void add(HTMLElement element, int before);
    public void remove(int index);
    public int getSelectedIndex();
    public void setSelectedIndex(int selectedIndex);
}
