// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLAllCollection extends HTMLCollection
{
    // HTMLAllCollection
    public Object namedItem(String name);
    public HTMLAllCollection tags(String tagName);
}
