// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLEmbedElement extends HTMLElement
{
    // HTMLEmbedElement
    public String getSrc();
    public void setSrc(String src);
    public String getType();
    public void setType(String type);
    public String getWidth();
    public void setWidth(String width);
    public String getHeight();
    public void setHeight(String height);
    // HTMLEmbedElement-15
    public String getAlign();
    public void setAlign(String align);
    public String getName();
    public void setName(String name);
}
