// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLLIElement extends HTMLElement
{
    // HTMLLIElement
    public int getValue();
    public void setValue(int value);
    // HTMLLIElement-23
    public String getType();
    public void setType(String type);
}
