// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLPreElement extends HTMLElement
{
    // HTMLPreElement
    // HTMLPreElement-31
    public int getWidth();
    public void setWidth(int width);
}
