// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLLabelElement extends HTMLElement
{
    // HTMLLabelElement
    public HTMLFormElement getForm();
    public String getHtmlFor();
    public void setHtmlFor(String htmlFor);
    public HTMLElement getControl();
}
