// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.NodeList;

public interface HTMLProgressElement extends HTMLElement
{
    // HTMLProgressElement
    public double getValue();
    public void setValue(double value);
    public double getMax();
    public void setMax(double max);
    public double getPosition();
    public NodeList getLabels();
}
