// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLImageElement extends HTMLElement
{
    // HTMLImageElement
    public String getAlt();
    public void setAlt(String alt);
    public String getSrc();
    public void setSrc(String src);
    public String getCrossOrigin();
    public void setCrossOrigin(String crossOrigin);
    public String getUseMap();
    public void setUseMap(String useMap);
    public boolean getIsMap();
    public void setIsMap(boolean isMap);
    public int getWidth();
    public void setWidth(int width);
    public int getHeight();
    public void setHeight(int height);
    public int getNaturalWidth();
    public int getNaturalHeight();
    public boolean getComplete();
    // HTMLImageElement-20
    public String getName();
    public void setName(String name);
    public String getAlign();
    public void setAlign(String align);
    public String getBorder();
    public void setBorder(String border);
    public int getHspace();
    public void setHspace(int hspace);
    public String getLongDesc();
    public void setLongDesc(String longDesc);
    public int getVspace();
    public void setVspace(int vspace);
}
