// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLParagraphElement extends HTMLElement
{
    // HTMLParagraphElement
    // HTMLParagraphElement-29
    public String getAlign();
    public void setAlign(String align);
}
