// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLOListElement extends HTMLElement
{
    // HTMLOListElement
    public boolean getReversed();
    public void setReversed(boolean reversed);
    public int getStart();
    public void setStart(int start);
    public String getType();
    public void setType(String type);
    // HTMLOListElement-28
    public boolean getCompact();
    public void setCompact(boolean compact);
}
