// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLDetailsElement extends HTMLElement
{
    // HTMLDetailsElement
    public boolean getOpen();
    public void setOpen(boolean open);
}
