// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLMetaElement extends HTMLElement
{
    // HTMLMetaElement
    public String getName();
    public void setName(String name);
    public String getHttpEquiv();
    public void setHttpEquiv(String httpEquiv);
    public String getContent();
    public void setContent(String content);
    // HTMLMetaElement-26
    public String getScheme();
    public void setScheme(String scheme);
}
