// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLFieldSetElement extends HTMLElement
{
    // HTMLFieldSetElement
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public HTMLFormElement getForm();
    public String getName();
    public void setName(String name);
    public String getType();
    public HTMLFormControlsCollection getElements();
    public boolean getWillValidate();
    public ValidityState getValidity();
    public String getValidationMessage();
    public boolean checkValidity();
    public void setCustomValidity(String error);
}
