// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLImageElement_Constructor
{
    // Constructor
    public HTMLImageElement createInstance();
    public HTMLImageElement createInstance(int width);
    public HTMLImageElement createInstance(int width, int height);
}
