// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLBaseElement extends HTMLElement
{
    // HTMLBaseElement
    public String getHref();
    public void setHref(String href);
    public String getTarget();
    public void setTarget(String target);
}
