// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.DOMTokenList;

public interface HTMLAnchorElement extends HTMLElement
{
    // HTMLAnchorElement
    public String getHref();
    public void setHref(String href);
    public String getTarget();
    public void setTarget(String target);
    public String getPing();
    public void setPing(String ping);
    public String getRel();
    public void setRel(String rel);
    public DOMTokenList getRelList();
    public String getMedia();
    public void setMedia(String media);
    public String getHreflang();
    public void setHreflang(String hreflang);
    public String getType();
    public void setType(String type);
    public String getText();
    public void setText(String text);
    public String getProtocol();
    public void setProtocol(String protocol);
    public String getHost();
    public void setHost(String host);
    public String getHostname();
    public void setHostname(String hostname);
    public String getPort();
    public void setPort(String port);
    public String getPathname();
    public void setPathname(String pathname);
    public String getSearch();
    public void setSearch(String search);
    public String getHash();
    public void setHash(String hash);
    // HTMLAnchorElement-7
    public String getCoords();
    public void setCoords(String coords);
    public String getCharset();
    public void setCharset(String charset);
    public String getName();
    public void setName(String name);
    public String getRev();
    public void setRev(String rev);
    public String getShape();
    public void setShape(String shape);
}
