// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLDirectoryElement extends HTMLElement
{
    // HTMLDirectoryElement
    public boolean getCompact();
    public void setCompact(boolean compact);
}
