// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLTableRowElement extends HTMLElement
{
    // HTMLTableRowElement
    public int getRowIndex();
    public int getSectionRowIndex();
    public HTMLCollection getCells();
    public HTMLElement insertCell();
    public HTMLElement insertCell(int index);
    public void deleteCell(int index);
    // HTMLTableRowElement-36
    public String getAlign();
    public void setAlign(String align);
    public String getBgColor();
    public void setBgColor(String bgColor);
    public String getCh();
    public void setCh(String ch);
    public String getChOff();
    public void setChOff(String chOff);
    public String getVAlign();
    public void setVAlign(String vAlign);
}
