// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.Document;

public interface HTMLObjectElement extends HTMLElement
{
    // HTMLObjectElement
    public String getData();
    public void setData(String data);
    public String getType();
    public void setType(String type);
    public boolean getTypeMustMatch();
    public void setTypeMustMatch(boolean typeMustMatch);
    public String getName();
    public void setName(String name);
    public String getUseMap();
    public void setUseMap(String useMap);
    public HTMLFormElement getForm();
    public String getWidth();
    public void setWidth(String width);
    public String getHeight();
    public void setHeight(String height);
    public Document getContentDocument();
    public Window getContentWindow();
    public boolean getWillValidate();
    public ValidityState getValidity();
    public String getValidationMessage();
    public boolean checkValidity();
    public void setCustomValidity(String error);
    // HTMLObjectElement-27
    public String getAlign();
    public void setAlign(String align);
    public String getArchive();
    public void setArchive(String archive);
    public String getBorder();
    public void setBorder(String border);
    public String getCode();
    public void setCode(String code);
    public String getCodeBase();
    public void setCodeBase(String codeBase);
    public String getCodeType();
    public void setCodeType(String codeType);
    public boolean getDeclare();
    public void setDeclare(boolean declare);
    public int getHspace();
    public void setHspace(int hspace);
    public String getStandby();
    public void setStandby(String standby);
    public int getVspace();
    public void setVspace(int vspace);
}
