// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.NodeList;

public interface HTMLMeterElement extends HTMLElement
{
    // HTMLMeterElement
    public double getValue();
    public void setValue(double value);
    public double getMin();
    public void setMin(double min);
    public double getMax();
    public void setMax(double max);
    public double getLow();
    public void setLow(double low);
    public double getHigh();
    public void setHigh(double high);
    public double getOptimum();
    public void setOptimum(double optimum);
    public NodeList getLabels();
}
