// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLStyleElement extends HTMLElement
{
    // HTMLStyleElement
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public String getMedia();
    public void setMedia(String media);
    public String getType();
    public void setType(String type);
    public boolean getScoped();
    public void setScoped(boolean scoped);
}
