// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLBaseFontElement extends HTMLElement
{
    // HTMLBaseFontElement
    public String getColor();
    public void setColor(String color);
    public String getFace();
    public void setFace(String face);
    public int getSize();
    public void setSize(int size);
}
