// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLTableSectionElement extends HTMLElement
{
    // HTMLTableSectionElement
    public HTMLCollection getRows();
    public HTMLElement insertRow();
    public HTMLElement insertRow(int index);
    public void deleteRow(int index);
    // HTMLTableSectionElement-34
    public String getAlign();
    public void setAlign(String align);
    public String getCh();
    public void setCh(String ch);
    public String getChOff();
    public void setChOff(String chOff);
    public String getVAlign();
    public void setVAlign(String vAlign);
}
