// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLAppletElement extends HTMLElement
{
    // HTMLAppletElement
    public String getAlign();
    public void setAlign(String align);
    public String getAlt();
    public void setAlt(String alt);
    public String getArchive();
    public void setArchive(String archive);
    public String getCode();
    public void setCode(String code);
    public String getCodeBase();
    public void setCodeBase(String codeBase);
    public String getHeight();
    public void setHeight(String height);
    public int getHspace();
    public void setHspace(int hspace);
    public String getName();
    public void setName(String name);
    public String getObject();
    public void setObject(String object);
    public int getVspace();
    public void setVspace(int vspace);
    public String getWidth();
    public void setWidth(String width);
}
