// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLTableElement extends HTMLElement
{
    // HTMLTableElement
    public HTMLTableCaptionElement getCaption();
    public void setCaption(HTMLTableCaptionElement caption);
    public HTMLElement createCaption();
    public void deleteCaption();
    public HTMLTableSectionElement getTHead();
    public void setTHead(HTMLTableSectionElement tHead);
    public HTMLElement createTHead();
    public void deleteTHead();
    public HTMLTableSectionElement getTFoot();
    public void setTFoot(HTMLTableSectionElement tFoot);
    public HTMLElement createTFoot();
    public void deleteTFoot();
    public HTMLCollection getTBodies();
    public HTMLElement createTBody();
    public HTMLCollection getRows();
    public HTMLElement insertRow();
    public HTMLElement insertRow(int index);
    public void deleteRow(int index);
    public String getBorder();
    public void setBorder(String border);
    // HTMLTableElement-33
    public String getAlign();
    public void setAlign(String align);
    public String getBgColor();
    public void setBgColor(String bgColor);
    public String getCellPadding();
    public void setCellPadding(String cellPadding);
    public String getCellSpacing();
    public void setCellSpacing(String cellSpacing);
    public String getFrame();
    public void setFrame(String frame);
    public String getRules();
    public void setRules(String rules);
    public String getSummary();
    public void setSummary(String summary);
    public String getWidth();
    public void setWidth(String width);
}
