// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLOptionElement extends HTMLElement
{
    // HTMLOptionElement
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public HTMLFormElement getForm();
    public String getLabel();
    public void setLabel(String label);
    public boolean getDefaultSelected();
    public void setDefaultSelected(boolean defaultSelected);
    public boolean getSelected();
    public void setSelected(boolean selected);
    public String getValue();
    public void setValue(String value);
    public String getText();
    public void setText(String text);
    public int getIndex();
}
