// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLSourceElement extends HTMLElement
{
    // HTMLSourceElement
    public String getSrc();
    public void setSrc(String src);
    public String getType();
    public void setType(String type);
    public String getMedia();
    public void setMedia(String media);
}
