// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.DOMSettableTokenList;
import org.w3c.dom.DOMTokenList;

public interface HTMLLinkElement extends HTMLElement
{
    // HTMLLinkElement
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public String getHref();
    public void setHref(String href);
    public String getRel();
    public void setRel(String rel);
    public DOMTokenList getRelList();
    public String getMedia();
    public void setMedia(String media);
    public String getHreflang();
    public void setHreflang(String hreflang);
    public String getType();
    public void setType(String type);
    public DOMSettableTokenList getSizes();
    public void setSizes(String sizes);
    // HTMLLinkElement-24
    public String getCharset();
    public void setCharset(String charset);
    public String getRev();
    public void setRev(String rev);
    public String getTarget();
    public void setTarget(String target);
}
