// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.DOMSettableTokenList;

public interface HTMLTableCellElement extends HTMLElement
{
    // HTMLTableCellElement
    public int getColSpan();
    public void setColSpan(int colSpan);
    public int getRowSpan();
    public void setRowSpan(int rowSpan);
    public DOMSettableTokenList getHeaders();
    public void setHeaders(String headers);
    public int getCellIndex();
    // HTMLTableCellElement-35
    public String getAbbr();
    public void setAbbr(String abbr);
    public String getAlign();
    public void setAlign(String align);
    public String getAxis();
    public void setAxis(String axis);
    public String getBgColor();
    public void setBgColor(String bgColor);
    public String getCh();
    public void setCh(String ch);
    public String getChOff();
    public void setChOff(String chOff);
    public String getHeight();
    public void setHeight(String height);
    public boolean getNoWrap();
    public void setNoWrap(boolean noWrap);
    public String getVAlign();
    public void setVAlign(String vAlign);
    public String getWidth();
    public void setWidth(String width);
}
