// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLBRElement extends HTMLElement
{
    // HTMLBRElement
    // HTMLBRElement-10
    public String getClear();
    public void setClear(String clear);
}
