// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLUListElement extends HTMLElement
{
    // HTMLUListElement
    // HTMLUListElement-37
    public boolean getCompact();
    public void setCompact(boolean compact);
    public String getType();
    public void setType(String type);
}
