// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLMenuElement extends HTMLElement
{
    // HTMLMenuElement
    public String getType();
    public void setType(String type);
    public String getLabel();
    public void setLabel(String label);
    // HTMLMenuElement-25
    public boolean getCompact();
    public void setCompact(boolean compact);
}
