// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLTrackElement extends HTMLElement
{
    // HTMLTrackElement
    public String getKind();
    public void setKind(String kind);
    public String getSrc();
    public void setSrc(String src);
    public String getSrclang();
    public void setSrclang(String srclang);
    public String getLabel();
    public void setLabel(String label);
    public boolean getDefault();
    public void setDefault(boolean _default);
    public TextTrack getTrack();
}
