// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLHtmlElement extends HTMLElement
{
    // HTMLHtmlElement
    // HTMLHtmlElement-18
    public String getVersion();
    public void setVersion(String version);
}
