// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.Element;

public interface HTMLCollection
{
    // HTMLCollection
    public int getLength();
    public Element item(int index);
    public Object namedItem(String name);
}
