// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLMapElement extends HTMLElement
{
    // HTMLMapElement
    public String getName();
    public void setName(String name);
    public HTMLCollection getAreas();
    public HTMLCollection getImages();
}
