// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.NodeList;

public interface HTMLButtonElement extends HTMLElement
{
    // HTMLButtonElement
    public boolean getAutofocus();
    public void setAutofocus(boolean autofocus);
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public HTMLFormElement getForm();
    public String getFormAction();
    public void setFormAction(String formAction);
    public String getFormEnctype();
    public void setFormEnctype(String formEnctype);
    public String getFormMethod();
    public void setFormMethod(String formMethod);
    public String getFormNoValidate();
    public void setFormNoValidate(String formNoValidate);
    public String getFormTarget();
    public void setFormTarget(String formTarget);
    public String getName();
    public void setName(String name);
    public String getType();
    public void setType(String type);
    public String getValue();
    public void setValue(String value);
    public boolean getWillValidate();
    public ValidityState getValidity();
    public String getValidationMessage();
    public boolean checkValidity();
    public void setCustomValidity(String error);
    public NodeList getLabels();
}
