// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.Document;

public interface HTMLFrameElement extends HTMLElement
{
    // HTMLFrameElement
    public String getFrameBorder();
    public void setFrameBorder(String frameBorder);
    public String getLongDesc();
    public void setLongDesc(String longDesc);
    public String getMarginHeight();
    public void setMarginHeight(String marginHeight);
    public String getMarginWidth();
    public void setMarginWidth(String marginWidth);
    public String getName();
    public void setName(String name);
    public boolean getNoResize();
    public void setNoResize(boolean noResize);
    public String getScrolling();
    public void setScrolling(String scrolling);
    public String getSrc();
    public void setSrc(String src);
    public Document getContentDocument();
    public Window getContentWindow();
}
