// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLAudioElement_Constructor
{
    // Constructor
    public HTMLAudioElement createInstance();
    public HTMLAudioElement createInstance(String src);
}
