// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.NodeList;

public interface HTMLTextAreaElement extends HTMLElement
{
    // HTMLTextAreaElement
    public boolean getAutofocus();
    public void setAutofocus(boolean autofocus);
    public int getCols();
    public void setCols(int cols);
    public String getDirName();
    public void setDirName(String dirName);
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public HTMLFormElement getForm();
    public int getMaxLength();
    public void setMaxLength(int maxLength);
    public String getName();
    public void setName(String name);
    public String getPlaceholder();
    public void setPlaceholder(String placeholder);
    public boolean getReadOnly();
    public void setReadOnly(boolean readOnly);
    public boolean getRequired();
    public void setRequired(boolean required);
    public int getRows();
    public void setRows(int rows);
    public String getWrap();
    public void setWrap(String wrap);
    public String getType();
    public String getDefaultValue();
    public void setDefaultValue(String defaultValue);
    public String getValue();
    public void setValue(String value);
    public int getTextLength();
    public boolean getWillValidate();
    public ValidityState getValidity();
    public String getValidationMessage();
    public boolean checkValidity();
    public void setCustomValidity(String error);
    public NodeList getLabels();
    public void select();
    public int getSelectionStart();
    public void setSelectionStart(int selectionStart);
    public int getSelectionEnd();
    public void setSelectionEnd(int selectionEnd);
    public String getSelectionDirection();
    public void setSelectionDirection(String selectionDirection);
    public void setSelectionRange(int start, int end);
    public void setSelectionRange(int start, int end, String direction);
}
