// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface HTMLHeadingElement extends HTMLElement
{
    // HTMLHeadingElement
    // HTMLHeadingElement-16
    public String getAlign();
    public void setAlign(String align);
}
