// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface Location
{
    // Location
    public String getHref();
    public void setHref(String href);
    public void assign(String url);
    public void replace(String url);
    public void reload();
    public String getProtocol();
    public void setProtocol(String protocol);
    public String getHost();
    public void setHost(String host);
    public String getHostname();
    public void setHostname(String hostname);
    public String getPort();
    public void setPort(String port);
    public String getPathname();
    public void setPathname(String pathname);
    public String getSearch();
    public void setSearch(String search);
    public String getHash();
    public void setHash(String hash);
    public String resolveURL(String url);
}
