// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface MediaController
{
    // MediaController
    public TimeRanges getBuffered();
    public TimeRanges getSeekable();
    public double getDuration();
    public double getCurrentTime();
    public void setCurrentTime(double currentTime);
    public boolean getPaused();
    public TimeRanges getPlayed();
    public void play();
    public void pause();
    public double getDefaultPlaybackRate();
    public void setDefaultPlaybackRate(double defaultPlaybackRate);
    public double getPlaybackRate();
    public void setPlaybackRate(double playbackRate);
    public double getVolume();
    public void setVolume(double volume);
    public boolean getMuted();
    public void setMuted(boolean muted);
    public Function getOnemptied();
    public void setOnemptied(Function onemptied);
    public Function getOnloadedmetadata();
    public void setOnloadedmetadata(Function onloadedmetadata);
    public Function getOnloadeddata();
    public void setOnloadeddata(Function onloadeddata);
    public Function getOncanplay();
    public void setOncanplay(Function oncanplay);
    public Function getOncanplaythrough();
    public void setOncanplaythrough(Function oncanplaythrough);
    public Function getOnplaying();
    public void setOnplaying(Function onplaying);
    public Function getOnended();
    public void setOnended(Function onended);
    public Function getOnwaiting();
    public void setOnwaiting(Function onwaiting);
    public Function getOndurationchange();
    public void setOndurationchange(Function ondurationchange);
    public Function getOntimeupdate();
    public void setOntimeupdate(Function ontimeupdate);
    public Function getOnplay();
    public void setOnplay(Function onplay);
    public Function getOnpause();
    public void setOnpause(Function onpause);
    public Function getOnratechange();
    public void setOnratechange(Function onratechange);
    public Function getOnvolumechange();
    public void setOnvolumechange(Function onvolumechange);
}
