// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface MediaError
{
    // MediaError
    public static final short MEDIA_ERR_ABORTED = 1;
    public static final short MEDIA_ERR_NETWORK = 2;
    public static final short MEDIA_ERR_DECODE = 3;
    public static final short MEDIA_ERR_SRC_NOT_SUPPORTED = 4;
    public short getCode();
}
