// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface MediaQueryList
{
    // MediaQueryList
    public String getMedia();
    public boolean getMatches();
    public void addListener(MediaQueryListListener listener);
    public void removeListener(MediaQueryListListener listener);
}
