// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface NavigatorUserMediaErrorCallback
{
    // NavigatorUserMediaErrorCallback
    public void handleEvent(NavigatorUserMediaError error);
}
