// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.events.Event;

public interface PopStateEvent extends Event
{
    // PopStateEvent
    public Object getState();
    public void initPopStateEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Object stateArg);
}
