// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.NodeList;

public interface RadioNodeList extends NodeList
{
    // RadioNodeList
    public String getValue();
    public void setValue(String value);
}
