// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface StreamTrack
{
    // StreamTrack
    public String getKind();
    public String getLabel();
    public boolean getEnabled();
    public void setEnabled(boolean enabled);
}
