// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.DocumentFragment;

public interface TextTrackCue
{
    // TextTrackCue
    public TextTrack getTrack();
    public String getId();
    public double getStartTime();
    public double getEndTime();
    public boolean getPauseOnExit();
    public String getDirection();
    public boolean getSnapToLines();
    public int getLinePosition();
    public int getTextPosition();
    public int getSize();
    public String getAlignment();
    public String getCueAsSource();
    public DocumentFragment getCueAsHTML();
    public Function getOnenter();
    public void setOnenter(Function onenter);
    public Function getOnexit();
    public void setOnexit(Function onexit);
}
