// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface TextTrackCueList
{
    // TextTrackCueList
    public int getLength();
    public TextTrackCue getElement(int index);
    public TextTrackCue getCueById(String id);
}
