// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface TextTrack
{
    // TextTrack
    public String getKind();
    public String getLabel();
    public String getLanguage();
    public static final short NONE = 0;
    public static final short LOADING = 1;
    public static final short LOADED = 2;
    public static final short ERROR = 3;
    public short getReadyState();
    public Function getOnload();
    public void setOnload(Function onload);
    public Function getOnerror();
    public void setOnerror(Function onerror);
    public static final short OFF = 0;
    public static final short HIDDEN = 1;
    public static final short SHOWING = 2;
    public short getMode();
    public void setMode(short mode);
    public TextTrackCueList getCues();
    public TextTrackCueList getActiveCues();
    public Function getOncuechange();
    public void setOncuechange(Function oncuechange);
}
