// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface TextTrackCue_Constructor
{
    // Constructor
    public TextTrackCue createInstance(String id, double startTime, double endTime, String text);
    public TextTrackCue createInstance(String id, double startTime, double endTime, String text, String settings);
    public TextTrackCue createInstance(String id, double startTime, double endTime, String text, String settings, boolean pauseOnExit);
}
