// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface TimeRanges
{
    // TimeRanges
    public int getLength();
    public double start(int index);
    public double end(int index);
}
