// Generated by esidl 0.4.0.

package org.w3c.dom.html;

import org.w3c.dom.events.Event;

public interface UndoManagerEvent extends Event
{
    // UndoManagerEvent
    public Object getData();
    public void initUndoManagerEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Object dataArg);
}
