// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface ValidityState
{
    // ValidityState
    public boolean getValueMissing();
    public boolean getTypeMismatch();
    public boolean getPatternMismatch();
    public boolean getTooLong();
    public boolean getRangeUnderflow();
    public boolean getRangeOverflow();
    public boolean getStepMismatch();
    public boolean getCustomError();
    public boolean getValid();
}
