// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface VideoTrack
{
    // VideoTrack
    public String getId();
    public String getKind();
    public String getLabel();
    public String getLanguage();
    public boolean getSelected();
    public void setSelected(boolean selected);
}
